In [1]:
import os

try:
    from google.colab import userdata
    hf_token = userdata.get("HF_TOKEN")
except Exception:
    hf_token = os.getenv("HF_TOKEN")

if hf_token:
    os.environ["HF_TOKEN"] = hf_token
    os.environ["HUGGING_FACE_HUB_TOKEN"] = hf_token
    print("HF token loaded from Colab Secret/environment.")
else:
    print("HF token not configured; public models may still work.")

HF token loaded from Kaggle Secrets.

In [2]:
!git clone https://github.com/TiiAyyLuvBear/Text-Mining---RAG-on-News

Cloning into 'Text-Mining---RAG-on-News'...
remote: Enumerating objects: 645, done.
remote: Counting objects: 100% (301/301), done.
remote: Compressing objects: 100% (157/157), done.
remote: Total 645 (delta 177), reused 259 (delta 144), pack-reused 344 (from 1)
Receiving objects: 100% (645/645), 22.11 MiB | 20.94 MiB/s, done.
Resolving deltas: 100% (351/351), done.

In [3]:
%cd Text-Mining---RAG-on-News
!git checkout test_feature_ta
!git fetch
!git pull
!pip install -r requirements.txt

/content/Text-Mining---RAG-on-News
Branch 'test_feature_ta' set up to track remote branch 'test_feature_ta' from 'origin'.
Switched to a new branch 'test_feature_ta'
Already up to date.
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 1)) (4.0.0)
Collecting llama-index (from -r requirements.txt (line 2))
  Downloading llama_index-0.14.23-py3-none-any.whl.metadata (14 kB)
Collecting langchain-text-splitters (from -r requirements.txt (line 3))
  Downloading langchain_text_splitters-1.1.2-py3-none-any.whl.metadata (3.3 kB)
Collecting llama-index-embeddings-huggingface (from -r requirements.txt (line 4))
  Downloading llama_index_embeddings_huggingface-0.7.0-py3-none-any.whl.metadata (459 bytes)
Collecting llama-index-retrievers-bm25 (from -r requirements.txt (line 5))
  Downloading llama_index_retrievers_bm25-0.7.1-py3-none-any.whl.metadata (447 bytes)
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 6)) (5.6.0)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 7)) (5.12.1)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 8)) (1.14.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 9)) (2.0.2)
Collecting chromadb (from -r requirements.txt (line 10))
  Downloading chromadb-1.5.9-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.0 kB)
Collecting llama-index-vector-stores-chroma (from -r requirements.txt (line 11))
  Downloading llama_index_vector_stores_chroma-0.5.5-py3-none-any.whl.metadata (413 bytes)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 12)) (2.2.2)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 14)) (6.0.3)
Requirement already satisfied: python-dotenv in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 15)) (1.2.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 16)) (4.67.3)
Requirement already satisfied: ipykernel in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 17)) (6.17.1)
Requirement already satisfied: notebook in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 18)) (6.5.7)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets->-r requirements.txt (line 1)) (3.29.4)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets->-r requirements.txt (line 1)) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets->-r requirements.txt (line 1)) (0.3.8)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets->-r requirements.txt (line 1)) (2.32.4)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets->-r requirements.txt (line 1)) (3.7.1)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets->-r requirements.txt (line 1)) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets->-r requirements.txt (line 1)) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from datasets->-r requirements.txt (line 1)) (1.20.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets->-r requirements.txt (line 1)) (26.2)
Collecting llama-index-core<0.15.0,>=0.14.23 (from llama-index->-r requirements.txt (line 2))
  Downloading llama_index_core-0.14.23-py3-none-any.whl.metadata (2.6 kB)
Collecting llama-index-embeddings-openai<0.7,>=0.6.0 (from llama-index->-r requirements.txt (line 2))
  Downloading llama_index_embeddings_openai-0.6.0-py3-none-any.whl.metadata (401 bytes)
Collecting llama-index-llms-openai<0.8,>=0.7.0 (from llama-index->-r requirements.txt (line 2))
  Downloading llama_index_llms_openai-0.7.9-py3-none-any.whl.metadata (3.0 kB)
Collecting nltk>=3.9.3 (from llama-index->-r requirements.txt (line 2))
  Downloading nltk-3.10.0-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.31 in /usr/local/lib/python3.12/dist-packages (from langchain-text-splitters->-r requirements.txt (line 3)) (1.4.8)
Collecting bm25s>=0.2.7.post1 (from llama-index-retrievers-bm25->-r requirements.txt (line 5))
  Downloading bm25s-0.3.9-py3-none-any.whl.metadata (29 kB)
Collecting pystemmer<3,>=2.2.0.1 (from llama-index-retrievers-bm25->-r requirements.txt (line 5))
  Downloading PyStemmer-2.2.0.3-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.2 kB)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers->-r requirements.txt (line 6)) (2.11.0+cu128)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers->-r requirements.txt (line 6)) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers->-r requirements.txt (line 6)) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers->-r requirements.txt (line 6)) (4.15.0)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers->-r requirements.txt (line 7)) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers->-r requirements.txt (line 7)) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers->-r requirements.txt (line 7)) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers->-r requirements.txt (line 7)) (0.8.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate->-r requirements.txt (line 8)) (5.9.5)
Collecting build>=1.0.3 (from chromadb->-r requirements.txt (line 10))
  Downloading build-1.5.1-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: pydantic>=2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb->-r requirements.txt (line 10)) (2.13.4)
Collecting pydantic-settings>=2.0 (from chromadb->-r requirements.txt (line 10))
  Downloading pydantic_settings-2.14.2-py3-none-any.whl.metadata (3.4 kB)
Collecting pybase64>=1.4.1 (from chromadb->-r requirements.txt (line 10))
  Downloading pybase64-1.4.3-cp312-cp312-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl.metadata (8.7 kB)
Requirement already satisfied: uvicorn>=0.18.3 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb->-r requirements.txt (line 10)) (0.49.0)
Collecting onnxruntime>=1.14.1 (from chromadb->-r requirements.txt (line 10))
  Downloading onnxruntime-1.27.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (5.4 kB)
Requirement already satisfied: opentelemetry-api>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb->-r requirements.txt (line 10)) (1.42.1)
Collecting opentelemetry-exporter-otlp-proto-grpc>=1.2.0 (from chromadb->-r requirements.txt (line 10))
  Downloading opentelemetry_exporter_otlp_proto_grpc-1.43.0-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb->-r requirements.txt (line 10)) (1.42.1)
Collecting pypika>=0.48.9 (from chromadb->-r requirements.txt (line 10))
  Downloading pypika-0.51.1-py2.py3-none-any.whl.metadata (51 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.0/52.0 kB 5.4 MB/s eta 0:00:00
Collecting overrides>=7.3.1 (from chromadb->-r requirements.txt (line 10))
  Downloading overrides-7.7.0-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.12/dist-packages (from chromadb->-r requirements.txt (line 10)) (7.1.0)
Requirement already satisfied: grpcio>=1.58.0 in /usr/local/lib/python3.12/dist-packages (from chromadb->-r requirements.txt (line 10)) (1.81.1)
Collecting bcrypt>=4.0.1 (from chromadb->-r requirements.txt (line 10))
  Downloading bcrypt-5.0.0-cp39-abi3-manylinux_2_34_x86_64.whl.metadata (10 kB)
Collecting kubernetes>=28.1.0 (from chromadb->-r requirements.txt (line 10))
  Downloading kubernetes-36.0.2-py2.py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: tenacity>=8.2.3 in /usr/local/lib/python3.12/dist-packages (from chromadb->-r requirements.txt (line 10)) (9.1.4)
Requirement already satisfied: mmh3>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from chromadb->-r requirements.txt (line 10)) (5.2.1)
Requirement already satisfied: orjson>=3.9.12 in /usr/local/lib/python3.12/dist-packages (from chromadb->-r requirements.txt (line 10)) (3.11.9)
Requirement already satisfied: httpx>=0.27.0 in /usr/local/lib/python3.12/dist-packages (from chromadb->-r requirements.txt (line 10)) (0.28.1)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.12/dist-packages (from chromadb->-r requirements.txt (line 10)) (13.9.4)
Requirement already satisfied: jsonschema>=4.19.0 in /usr/local/lib/python3.12/dist-packages (from chromadb->-r requirements.txt (line 10)) (4.26.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->-r requirements.txt (line 12)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->-r requirements.txt (line 12)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->-r requirements.txt (line 12)) (2026.2)
Requirement already satisfied: debugpy>=1.0 in /usr/local/lib/python3.12/dist-packages (from ipykernel->-r requirements.txt (line 17)) (1.8.15)
Requirement already satisfied: ipython>=7.23.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel->-r requirements.txt (line 17)) (7.34.0)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.12/dist-packages (from ipykernel->-r requirements.txt (line 17)) (7.4.9)
Requirement already satisfied: matplotlib-inline>=0.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel->-r requirements.txt (line 17)) (0.2.2)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.12/dist-packages (from ipykernel->-r requirements.txt (line 17)) (1.6.0)
Requirement already satisfied: pyzmq>=17 in /usr/local/lib/python3.12/dist-packages (from ipykernel->-r requirements.txt (line 17)) (26.2.1)
Requirement already satisfied: tornado>=6.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel->-r requirements.txt (line 17)) (6.5.7)
Requirement already satisfied: traitlets>=5.1.0 in /usr/local/lib/python3.12/dist-packages (from ipykernel->-r requirements.txt (line 17)) (5.7.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from notebook->-r requirements.txt (line 18)) (3.1.6)
Requirement already satisfied: argon2-cffi in /usr/local/lib/python3.12/dist-packages (from notebook->-r requirements.txt (line 18)) (25.1.0)
Requirement already satisfied: jupyter-core>=4.6.1 in /usr/local/lib/python3.12/dist-packages (from notebook->-r requirements.txt (line 18)) (5.9.1)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.12/dist-packages (from notebook->-r requirements.txt (line 18)) (0.2.0)
Requirement already satisfied: nbformat in /usr/local/lib/python3.12/dist-packages (from notebook->-r requirements.txt (line 18)) (5.10.4)
Requirement already satisfied: nbconvert>=5 in /usr/local/lib/python3.12/dist-packages (from notebook->-r requirements.txt (line 18)) (7.17.1)
Requirement already satisfied: Send2Trash>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from notebook->-r requirements.txt (line 18)) (2.1.0)
Requirement already satisfied: terminado>=0.8.3 in /usr/local/lib/python3.12/dist-packages (from notebook->-r requirements.txt (line 18)) (0.18.1)
Requirement already satisfied: prometheus-client in /usr/local/lib/python3.12/dist-packages (from notebook->-r requirements.txt (line 18)) (0.25.0)
Requirement already satisfied: nbclassic>=0.4.7 in /usr/local/lib/python3.12/dist-packages (from notebook->-r requirements.txt (line 18)) (1.3.3)
Collecting pyproject_hooks (from build>=1.0.3->chromadb->-r requirements.txt (line 10))
  Downloading pyproject_hooks-1.2.0-py3-none-any.whl.metadata (1.3 kB)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets->-r requirements.txt (line 1)) (3.14.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb->-r requirements.txt (line 10)) (4.14.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb->-r requirements.txt (line 10)) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb->-r requirements.txt (line 10)) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb->-r requirements.txt (line 10)) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.27.0->chromadb->-r requirements.txt (line 10)) (0.16.0)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets->-r requirements.txt (line 1)) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets->-r requirements.txt (line 1)) (1.5.1)
WARNING: huggingface-hub 1.20.1 does not provide the extra 'inference'
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel->-r requirements.txt (line 17)) (75.2.0)
Collecting jedi>=0.16 (from ipython>=7.23.1->ipykernel->-r requirements.txt (line 17))
  Downloading jedi-0.20.0-py2.py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel->-r requirements.txt (line 17)) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel->-r requirements.txt (line 17)) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel->-r requirements.txt (line 17)) (3.0.52)
Requirement already satisfied: pygments in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel->-r requirements.txt (line 17)) (2.20.0)
Requirement already satisfied: backcall in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel->-r requirements.txt (line 17)) (0.2.0)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel->-r requirements.txt (line 17)) (4.9.0)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb->-r requirements.txt (line 10)) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb->-r requirements.txt (line 10)) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb->-r requirements.txt (line 10)) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb->-r requirements.txt (line 10)) (2026.5.1)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->ipykernel->-r requirements.txt (line 17)) (0.4)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core>=4.6.1->notebook->-r requirements.txt (line 18)) (4.10.0)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb->-r requirements.txt (line 10)) (1.17.0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb->-r requirements.txt (line 10)) (1.9.0)
Requirement already satisfied: requests-oauthlib in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb->-r requirements.txt (line 10)) (2.0.0)
Requirement already satisfied: urllib3!=2.6.0,>=1.24.2 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb->-r requirements.txt (line 10)) (2.5.0)
Collecting durationpy>=0.7 (from kubernetes>=28.1.0->chromadb->-r requirements.txt (line 10))
  Downloading durationpy-0.10-py3-none-any.whl.metadata (340 bytes)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain-text-splitters->-r requirements.txt (line 3)) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.17 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain-text-splitters->-r requirements.txt (line 3)) (0.0.18)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain-text-splitters->-r requirements.txt (line 3)) (0.9.1)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain-text-splitters->-r requirements.txt (line 3)) (0.16.2)
Requirement already satisfied: aiosqlite in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.23->llama-index->-r requirements.txt (line 2)) (0.22.1)
Collecting banks<3,>=2.3.0 (from llama-index-core<0.15.0,>=0.14.23->llama-index->-r requirements.txt (line 2))
  Downloading banks-2.4.5-py3-none-any.whl.metadata (12 kB)
Collecting dataclasses-json (from llama-index-core<0.15.0,>=0.14.23->llama-index->-r requirements.txt (line 2))
  Downloading dataclasses_json-0.6.7-py3-none-any.whl.metadata (25 kB)
Collecting deprecated>=1.2.9.3 (from llama-index-core<0.15.0,>=0.14.23->llama-index->-r requirements.txt (line 2))
  Downloading deprecated-1.3.1-py2.py3-none-any.whl.metadata (5.9 kB)
Collecting dirtyjson<2,>=1.0.8 (from llama-index-core<0.15.0,>=0.14.23->llama-index->-r requirements.txt (line 2))
  Downloading dirtyjson-1.0.8-py3-none-any.whl.metadata (11 kB)
Collecting filetype<2,>=1.2.0 (from llama-index-core<0.15.0,>=0.14.23->llama-index->-r requirements.txt (line 2))
  Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting llama-index-workflows<3,>=2.14.0 (from llama-index-core<0.15.0,>=0.14.23->llama-index->-r requirements.txt (line 2))
  Downloading llama_index_workflows-2.22.2-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: networkx>=3.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.23->llama-index->-r requirements.txt (line 2)) (3.6.1)

In [4]:
%cd Text-Mining---RAG-on-News

[Errno 2] No such file or directory: 'Text-Mining---RAG-on-News'
/content/Text-Mining---RAG-on-News

In [5]:
from pathlib import Path
import json
import subprocess
import sys
import time

import pandas as pd
from IPython.display import display, Markdown

PROJECT_ROOT = Path.cwd()
while PROJECT_ROOT != PROJECT_ROOT.parent and not (PROJECT_ROOT / "src").exists():
    PROJECT_ROOT = PROJECT_ROOT.parent

print("Project root:", PROJECT_ROOT)

Project root: /content/Text-Mining---RAG-on-News

## 1. Cấu hình

- `RAW_CSV_PATH`: CSV đầu vào cho `src.data_ingestion.cli`.
- `ARTICLE_LIMIT`: số article đưa vào chunking/embedding. Đặt `None` để chạy full corpus.
- `STRATEGIES`: các chiến thuật chunking cần embed.
- `BATCH_SIZE`: CPU nên bắt đầu thấp, ví dụ 4 hoặc 8.

In [6]:
# Chọn một CSV đang có trong repo. Có thể đổi sang validation_new.csv/test_new.csv hoặc CSV tổng của bạn.
RAW_CSV_PATH = PROJECT_ROOT / "Dataset" / "Create_QA_Vietonline" / "VietOnlineNews" / "train_new.csv"

PROCESSED_JSONL = PROJECT_ROOT / "src" / "embed" / "output" / "data" / "vieonline_news_clean.jsonl"
REVIEW_JSONL = PROJECT_ROOT / "src" / "embed" / "output" / "data" / "vieonline_news_human_review.jsonl"
CHUNK_OUTPUT_DIR = PROJECT_ROOT / "src" / "embed" / "output" / "chunks"
DENSE_OUTPUT_ROOT = PROJECT_ROOT / "src" / "embed" / "output" / "dense"
SAMPLE_REPORT = PROJECT_ROOT / "src" / "embed" / "output" / "embedding_strategy_samples.md"

# CPU-friendly default. Đặt None để chạy toàn bộ file sau khi đã smoke test.
ARTICLE_LIMIT = None
STRATEGIES = ["token", "llamaindex", "structured", "langchain_recursive"]  # thêm "langchain_recursive" nếu muốn so sánh đủ 4 strategy

CHUNK_SIZE = 400
OVERLAP = 80
SMALL_ARTICLE_CHARS = 1000
BATCH_SIZE = 4
MODEL_NAME = "intfloat/multilingual-e5-large"
SAMPLE_SIZE = 5

for path in [PROCESSED_JSONL.parent, CHUNK_OUTPUT_DIR, DENSE_OUTPUT_ROOT, SAMPLE_REPORT.parent]:
    path.mkdir(parents=True, exist_ok=True)

config = {
    "raw_csv": str(RAW_CSV_PATH),
    "processed_jsonl": str(PROCESSED_JSONL),
    "chunk_output_dir": str(CHUNK_OUTPUT_DIR),
    "dense_output_root": str(DENSE_OUTPUT_ROOT),
    "article_limit": ARTICLE_LIMIT,
    "strategies": STRATEGIES,
    "chunk_size": CHUNK_SIZE,
    "overlap": OVERLAP,
    "batch_size": BATCH_SIZE,
    "model_name": MODEL_NAME,
}
display(config)

{'raw_csv': '/content/Text-Mining---RAG-on-News/Dataset/Create_QA_Vietonline/VietOnlineNews/train_new.csv',
 'processed_jsonl': '/content/Text-Mining---RAG-on-News/src/embed/output/data/vieonline_news_clean.jsonl',
 'chunk_output_dir': '/content/Text-Mining---RAG-on-News/src/embed/output/chunks',
 'dense_output_root': '/content/Text-Mining---RAG-on-News/src/embed/output/dense',
 'article_limit': None,
 'strategies': ['token', 'llamaindex', 'structured', 'langchain_recursive'],
 'chunk_size': 400,
 'overlap': 80,
 'batch_size': 4,
 'model_name': 'intfloat/multilingual-e5-large'}

## 2. Helper chạy CLI có streaming output

Các lệnh bên dưới dùng `sys.executable -m ...` để chạy đúng Python environment của notebook. Output được stream trực tiếp để thấy progress bar của chunking và embedding.

In [7]:
def run_cli(args, cwd=PROJECT_ROOT):
    args = [str(item) for item in args]
    printable = " ".join(args)
    print(f"\n$ {printable}\n")
    started = time.perf_counter()
    process = subprocess.Popen(
        args,
        cwd=str(cwd),
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        encoding="utf-8",
        errors="replace",
        bufsize=1,
    )
    lines = []
    assert process.stdout is not None
    for line in process.stdout:
        print(line, end="")
        lines.append(line)
    return_code = process.wait()
    elapsed = time.perf_counter() - started
    print(f"\n[exit={return_code}] elapsed={elapsed:.2f}s")
    if return_code != 0:
        raise RuntimeError(f"Command failed: {printable}")
    return "".join(lines)

## 3. Data ingestion

In [8]:
ingest_cmd = [
    sys.executable, "-m", "src.data_ingestion.cli",
    "--input", RAW_CSV_PATH,
    "--output", PROCESSED_JSONL,
    "--review-output", REVIEW_JSONL,
]
run_cli(ingest_cmd)

$ /usr/bin/python3 -m src.data_ingestion.cli --input /content/Text-Mining---RAG-on-News/Dataset/Create_QA_Vietonline/VietOnlineNews/train_new.csv --output /content/Text-Mining---RAG-on-News/src/embed/output/data/vieonline_news_clean.jsonl --review-output /content/Text-Mining---RAG-on-News/src/embed/output/data/vieonline_news_human_review.jsonl

{
  "rows_read": 10073,
  "rows_written": 10073,
  "missing_required": 0,
  "short_content": 13,
  "long_content": 3,
  "html_like": 3,
  "url_like": 0
}

[exit=0] elapsed=32.27s

'{\n  "rows_read": 10073,\n  "rows_written": 10073,\n  "missing_required": 0,\n  "short_content": 13,\n  "long_content": 3,\n  "html_like": 3,\n  "url_like": 0\n}\n'

## 4. Chunking theo strategy

Bước này dùng CLI `src.chunking.cli`. Nếu chạy CPU, giữ `ARTICLE_LIMIT` nhỏ trước để giảm thời gian embed sau đó.

In [9]:
chunk_cmd = [
    sys.executable, "-m", "src.chunking.cli",
    "--input", PROCESSED_JSONL,
    "--output-dir", CHUNK_OUTPUT_DIR,
    "--strategies", *STRATEGIES,
    "--chunk-size", CHUNK_SIZE,
    "--overlap", OVERLAP,
    "--small-article-chars", SMALL_ARTICLE_CHARS,
]
if ARTICLE_LIMIT is not None:
    chunk_cmd += ["--limit", ARTICLE_LIMIT]
run_cli(chunk_cmd)

$ /usr/bin/python3 -m src.chunking.cli --input /content/Text-Mining---RAG-on-News/src/embed/output/data/vieonline_news_clean.jsonl --output-dir /content/Text-Mining---RAG-on-News/src/embed/output/chunks --strategies token llamaindex structured langchain_recursive --chunk-size 400 --overlap 80 --small-article-chars 1000

Starting chunking: 10073 article(s), 4 strategy(ies), output_dir=/content/Text-Mining---RAG-on-News/src/embed/output/chunks

Chunking [token]:   0%|          | 0/10073 [00:00<?, ?article/s]
Chunking [token]:   1%|          | 121/10073 [00:00<00:08, 1200.61article/s]
Chunking [token]:   2%|▏         | 242/10073 [00:00<00:08, 1093.33article/s]
Chunking [token]:   4%|▎         | 363/10073 [00:00<00:08, 1140.54article/s]
Chunking [token]:   5%|▍         | 494/10073 [00:00<00:07, 1199.17article/s]
Chunking [token]:   6%|▌         | 615/10073 [00:00<00:08, 1158.67article/s]
Chunking [token]:   7%|▋         | 744/10073 [00:00<00:07, 1196.78article/s]
Chunking [token]:   9%|▊         | 866/10073 [00:00<00:07, 1203.64article/s]
Chunking [token]:  10%|▉         | 987/10073 [00:00<00:07, 1198.63article/s]
Chunking [token]:  11%|█         | 1123/10073 [00:00<00:07, 1246.44article/s]
Chunking [token]:  12%|█▏        | 1248/10073 [00:01<00:07, 1188.55article/s]
Chunking [token]:  14%|█▍        | 1443/10073 [00:01<00:06, 1409.66article/s]
Chunking [token]:  17%|█▋        | 1665/10073 [00:01<00:05, 1646.43article/s]
Chunking [token]:  19%|█▊        | 1876/10073 [00:01<00:04, 1780.52article/s]
Chunking [token]:  21%|██        | 2089/10073 [00:01<00:04, 1884.22article/s]
Chunking [token]:  23%|██▎       | 2287/10073 [00:01<00:04, 1910.15article/s]
Chunking [token]:  25%|██▍       | 2479/10073 [00:01<00:04, 1888.84article/s]
Chunking [token]:  27%|██▋       | 2683/10073 [00:01<00:03, 1931.86article/s]
Chunking [token]:  29%|██▉       | 2902/10073 [00:01<00:03, 2007.32article/s]
Chunking [token]:  31%|███       | 3125/10073 [00:01<00:03, 2073.54article/s]
Chunking [token]:  33%|███▎      | 3344/10073 [00:02<00:03, 2107.01article/s]
Chunking [token]:  35%|███▌      | 3555/10073 [00:02<00:03, 2032.82article/s]
Chunking [token]:  38%|███▊      | 3785/10073 [00:02<00:02, 2110.12article/s]
Chunking [token]:  40%|███▉      | 3997/10073 [00:02<00:02, 2088.08article/s]
Chunking [token]:  42%|████▏     | 4213/10073 [00:02<00:02, 2108.04article/s]
Chunking [token]:  44%|████▍     | 4425/10073 [00:02<00:02, 2105.67article/s]
Chunking [token]:  46%|████▌     | 4636/10073 [00:02<00:02, 1998.64article/s]
Chunking [token]:  48%|████▊     | 4848/10073 [00:02<00:02, 2032.14article/s]
Chunking [token]:  50%|█████     | 5055/10073 [00:02<00:02, 2041.61article/s]
Chunking [token]:  52%|█████▏    | 5264/10073 [00:02<00:02, 2055.15article/s]
Chunking [token]:  54%|█████▍    | 5471/10073 [00:03<00:02, 2039.04article/s]
Chunking [token]:  56%|█████▋    | 5676/10073 [00:03<00:02, 2014.24article/s]
Chunking [token]:  58%|█████▊    | 5878/10073 [00:03<00:02, 1994.82article/s]
Chunking [token]:  60%|██████    | 6078/10073 [00:03<00:02, 1949.67article/s]
Chunking [token]:  62%|██████▏   | 6288/10073 [00:03<00:01, 1992.72article/s]
Chunking [token]:  65%|██████▍   | 6503/10073 [00:03<00:01, 2037.67article/s]
Chunking [token]:  67%|██████▋   | 6708/10073 [00:03<00:01, 2005.10article/s]
Chunking [token]:  69%|██████▉   | 6936/10073 [00:03<00:01, 2084.58article/s]
Chunking [token]:  71%|███████   | 7158/10073 [00:03<00:01, 2120.53article/s]
Chunking [token]:  73%|███████▎  | 7377/10073 [00:04<00:01, 2138.99article/s]
Chunking [token]:  75%|███████▌  | 7592/10073 [00:04<00:01, 2106.99article/s]
Chunking [token]:  77%|███████▋  | 7803/10073 [00:04<00:01, 2047.81article/s]
Chunking [token]:  80%|███████▉  | 8009/10073 [00:04<00:01, 1756.81article/s]
Chunking [token]:  82%|████████▏ | 8216/10073 [00:04<00:01, 1838.59article/s]
Chunking [token]:  84%|████████▎ | 8412/10073 [00:04<00:00, 1871.21article/s]
Chunking [token]:  86%|████████▌ | 8619/10073 [00:04<00:00, 1906.89article/s]
Chunking [token]:  88%|████████▊ | 8814/10073 [00:04<00:00, 1905.70article/s]
Chunking [token]:  89%|████████▉ | 9009/10073 [00:04<00:00, 1912.74article/s]
Chunking [token]:  92%|█████████▏| 9234/10073 [00:05<00:00, 2010.51article/s]
Chunking [token]:  94%|█████████▍| 9463/10073 [00:05<00:00, 2092.31article/s]
Chunking [token]:  96%|█████████▌| 9674/10073 [00:05<00:00, 2078.41article/s]
Chunking [token]:  98%|█████████▊| 9889/10073 [00:05<00:00, 2099.05article/s]
Chunking [token]: 100%|██████████| 10073/10073 [00:05<00:00, 1866.14article/s]
Completed token: 10073 article(s), 24099 chunk(s), 5.39781s -> /content/Text-Mining---RAG-on-News/src/embed/output/chunks/vieonline_news_chunks_token.jsonl
{
  "token": {
    "output_path": "/content/Text-Mining---RAG-on-News/src/embed/output/chunks/vieonline_news_chunks_token.jsonl",
    "config": {
      "strategy": "token",
      "chunk_size": 400,
      "overlap": 80,
      "min_chunk_tokens": 80,
      "small_article_chars": 1000,
      "max_chunks_per_article": null,
      "inject_title_description": true
    },
    "stats": {
      "articles_read": 10073,
      "chunks_written": 24099,
      "short_articles": 13,
      "truncated_articles": 0,
      "empty_articles": 0,
      "total_chunk_tokens": 8034815,
      "total_chunk_chars": 36876593,
      "min_chunk_tokens": 50,
      "max_chunk_tokens": 400,
      "min_chunk_chars": 221,
      "max_chunk_chars": 2869,
      "elapsed_seconds": 5.39781,
      "avg_chunks_per_article": 2.3924,
      "avg_chunk_tokens": 333.4086,
      "avg_chunk_chars": 1530.2126,
      "chunks_per_second": 4464.5884
    }
  }
}

Chunking [llamaindex]:   0%|          | 0/10073 [00:00<?, ?article/s]
Chunking [llamaindex]:   0%|          | 1/10073 [00:04<11:31:13,  4.12s/article]
Chunking [llamaindex]:   0%|          | 41/10073 [00:04<12:15, 13.64article/s]
Chunking [llamaindex]:   1%|          | 76/10073 [00:04<05:45, 28.95article/s]
Chunking [llamaindex]:   1%|          | 118/10073 [00:04<03:08, 52.82article/s]
Chunking [llamaindex]:   2%|▏         | 152/10073 [00:04<02:11, 75.50article/s]
Chunking [llamaindex]:   2%|▏         | 189/10073 [00:04<01:33, 105.36article/s]
Chunking [llamaindex]:   2%|▏         | 225/10073 [00:04<01:11, 137.17article/s]
Chunking [llamaindex]:   3%|▎         | 260/10073 [00:04<00:58, 166.71article/s]
Chunking [llamaindex]:   3%|▎         | 295/10073 [00:04<00:49, 198.80article/s]
Chunking [llamaindex]:   3%|▎         | 334/10073 [00:05<00:41, 236.58article/s]
Chunking [llamaindex]:   4%|▎         | 372/10073 [00:05<00:36, 268.15article/s]
Chunking [llamaindex]:   4%|▍         | 409/10073 [00:05<00:33, 291.13article/s]
Chunking [llamaindex]:   4%|▍         | 446/10073 [00:05<00:31, 308.50article/s]
Chunking [llamaindex]:   5%|▍         | 482/10073 [00:05<00:29, 321.26article/s]
Chunking [llamaindex]:   5%|▌         | 518/10073 [00:05<00:31, 302.54article/s]
Chunking [llamaindex]:   5%|▌         | 552/10073 [00:05<00:33, 288.48article/s]
Chunking [llamaindex]:   6%|▌         | 583/10073 [00:05<00:35, 266.57article/s]
Chunking [llamaindex]:   6%|▌         | 612/10073 [00:05<00:36, 262.39article/s]
Chunking [llamaindex]:   6%|▋         | 640/10073 [00:06<00:39, 240.96article/s]
Chunking [llamaindex]:   7%|▋         | 666/10073 [00:06<00:38, 244.42article/s]
Chunking [llamaindex]:   7%|▋         | 692/10073 [00:06<00:40, 233.40article/s]
Chunking [llamaindex]:   7%|▋         | 718/10073 [00:06<00:39, 239.03article/s]
Chunking [llamaindex]:   7%|▋         | 744/10073 [00:06<00:38, 241.23article/s]
Chunking [llamaindex]:   8%|▊         | 769/10073 [00:06<00:39, 233.45article/s]
Chunking [llamaindex]:   8%|▊         | 793/10073 [00:06<00:39, 233.83article/s]
Chunking [llamaindex]:   8%|▊         | 819/10073 [00:06<00:38, 238.99article/s]
Chunking [llamaindex]:   8%|▊         | 844/10073 [00:07<00:40, 225.39article/s]
Chunking [llamaindex]:   9%|▊         | 868/10073 [00:07<00:40, 228.75article/s]
Chunking [llamaindex]:   9%|▉         | 892/10073 [00:07<00:40, 224.98article/s]
Chunking [llamaindex]:   9%|▉         | 915/10073 [00:07<00:41, 220.35article/s]
Chunking [llamaindex]:   9%|▉         | 941/10073 [00:07<00:40, 228.14article/s]
Chunking [llamaindex]:  10%|▉         | 965/10073 [00:07<00:40, 226.56article/s]
Chunking [llamaindex]:  10%|▉         | 990/10073 [00:07<00:39, 230.88article/s]
Chunking [llamaindex]:  10%|█         | 1014/10073 [00:07<00:39, 229.88article/s]
Chunking [llamaindex]:  10%|█         | 1038/10073 [00:07<00:39, 225.95article/s]
Chunking [llamaindex]:  11%|█         | 1061/10073 [00:07<00:40, 224.03article/s]
Chunking [llamaindex]:  11%|█         | 1090/10073 [00:08<00:37, 242.26article/s]
Chunking [llamaindex]:  11%|█         | 1125/10073 [00:08<00:32, 271.68article/s]
Chunking [llamaindex]:  12%|█▏        | 1161/10073 [00:08<00:30, 296.98article/s]
Chunking [llamaindex]:  12%|█▏        | 1199/10073 [00:08<00:27, 319.99article/s]
Chunking [llamaindex]:  12%|█▏        | 1232/10073 [00:08<00:27, 316.31article/s]
Chunking [llamaindex]:  13%|█▎        | 1268/10073 [00:08<00:26, 327.76article/s]
Chunking [llamaindex]:  13%|█▎        | 1304/10073 [00:08<00:26, 332.60article/s]
Chunking [llamaindex]:  13%|█▎        | 1338/10073 [00:08<00:26, 325.96article/s]
Chunking [llamaindex]:  14%|█▎        | 1378/10073 [00:08<00:25, 346.03article/s]
Chunking [llamaindex]:  14%|█▍        | 1414/10073 [00:08<00:25, 346.14article/s]
Chunking [llamaindex]:  14%|█▍        | 1456/10073 [00:09<00:23, 367.50article/s]
Chunking [llamaindex]:  15%|█▍        | 1498/10073 [00:09<00:22, 380.40article/s]
Chunking [llamaindex]:  15%|█▌        | 1539/10073 [00:09<00:21, 388.67article/s]
Chunking [llamaindex]:  16%|█▌        | 1578/10073 [00:09<00:22, 372.19article/s]
Chunking [llamaindex]:  16%|█▌        | 1616/10073 [00:09<00:22, 369.15article/s]
Chunking [llamaindex]:  16%|█▋        | 1654/10073 [00:09<00:22, 371.82article/s]
Chunking [llamaindex]:  17%|█▋        | 1692/10073 [00:09<00:24, 344.69article/s]
Chunking [llamaindex]:  17%|█▋        | 1727/10073 [00:09<00:24, 337.15article/s]
Chunking [llamaindex]:  18%|█▊        | 1766/10073 [00:09<00:23, 349.58article/s]
Chunking [llamaindex]:  18%|█▊        | 1807/10073 [00:10<00:22, 364.60article/s]
Chunking [llamaindex]:  18%|█▊        | 1848/10073 [00:10<00:21, 375.45article/s]
Chunking [llamaindex]:  19%|█▉        | 1889/10073 [00:10<00:21, 382.60article/s]
Chunking [llamaindex]:  19%|█▉        | 1928/10073 [00:10<00:22, 369.15article/s]
Chunking [llamaindex]:  20%|█▉        | 1966/10073 [00:10<00:21, 372.09article/s]
Chunking [llamaindex]:  20%|█▉        | 2004/10073 [00:10<00:22, 352.98article/s]
Chunking [llamaindex]:  20%|██        | 2040/10073 [00:10<00:22, 352.42article/s]
Chunking [llamaindex]:  21%|██        | 2079/10073 [00:10<00:22, 362.92article/s]
Chunking [llamaindex]:  21%|██        | 2116/10073 [00:10<00:21, 362.99article/s]
Chunking [llamaindex]:  21%|██▏       | 2154/10073 [00:11<00:21, 360.50article/s]
Chunking [llamaindex]:  22%|██▏       | 2191/10073 [00:11<00:22, 355.11article/s]
Chunking [llamaindex]:  22%|██▏       | 2234/10073 [00:11<00:21, 372.42article/s]
Chunking [llamaindex]:  23%|██▎       | 2274/10073 [00:11<00:20, 378.94article/s]
Chunking [llamaindex]:  23%|██▎       | 2312/10073 [00:11<00:21, 369.31article/s]
Chunking [llamaindex]:  23%|██▎       | 2352/10073 [00:11<00:20, 376.28article/s]
Chunking [llamaindex]:  24%|██▎       | 2390/10073 [00:11<00:21, 365.00article/s]
Chunking [llamaindex]:  24%|██▍       | 2431/10073 [00:11<00:20, 376.28article/s]
Chunking [llamaindex]:  25%|██▍       | 2469/10073 [00:11<00:20, 363.67article/s]
Chunking [llamaindex]:  25%|██▍       | 2511/10073 [00:11<00:19, 379.09article/s]
Chunking [llamaindex]:  25%|██▌       | 2550/10073 [00:12<00:20, 374.32article/s]
Chunking [llamaindex]:  26%|██▌       | 2588/10073 [00:12<00:20, 373.31article/s]
Chunking [llamaindex]:  26%|██▌       | 2626/10073 [00:12<00:19, 374.45article/s]
Chunking [llamaindex]:  26%|██▋       | 2664/10073 [00:12<00:21, 350.15article/s]
Chunking [llamaindex]:  27%|██▋       | 2702/10073 [00:12<00:20, 355.70article/s]
Chunking [llamaindex]:  27%|██▋       | 2744/10073 [00:12<00:19, 370.26article/s]
Chunking [llamaindex]:  28%|██▊       | 2783/10073 [00:12<00:19, 373.57article/s]
Chunking [llamaindex]:  28%|██▊       | 2828/10073 [00:12<00:18, 394.74article/s]
Chunking [llamaindex]:  28%|██▊       | 2868/10073 [00:12<00:21, 338.30article/s]
Chunking [llamaindex]:  29%|██▉       | 2904/10073 [00:13<00:21, 339.77article/s]
Chunking [llamaindex]:  29%|██▉       | 2949/10073 [00:13<00:19, 367.70article/s]
Chunking [llamaindex]:  30%|██▉       | 2987/10073 [00:13<00:19, 364.86article/s]
Chunking [llamaindex]:  30%|███       | 3025/10073 [00:13<00:19, 357.36article/s]
Chunking [llamaindex]:  30%|███       | 3067/10073 [00:13<00:18, 374.79article/s]
Chunking [llamaindex]:  31%|███       | 3105/10073 [00:13<00:18, 370.37article/s]
Chunking [llamaindex]:  31%|███       | 3143/10073 [00:13<00:18, 367.10article/s]
Chunking [llamaindex]:  32%|███▏      | 3183/10073 [00:13<00:18, 375.46article/s]
Chunking [llamaindex]:  32%|███▏      | 3224/10073 [00:13<00:17, 382.16article/s]
Chunking [llamaindex]:  32%|███▏      | 3263/10073 [00:14<00:18, 363.27article/s]
Chunking [llamaindex]:  33%|███▎      | 3300/10073 [00:14<00:19, 355.93article/s]
Chunking [llamaindex]:  33%|███▎      | 3340/10073 [00:14<00:18, 365.74article/s]
Chunking [llamaindex]:  34%|███▎      | 3377/10073 [00:14<00:19, 345.32article/s]
Chunking [llamaindex]:  34%|███▍      | 3415/10073 [00:14<00:18, 352.69article/s]
Chunking [llamaindex]:  34%|███▍      | 3455/10073 [00:14<00:18, 365.73article/s]
Chunking [llamaindex]:  35%|███▍      | 3493/10073 [00:14<00:17, 368.06article/s]
Chunking [llamaindex]:  35%|███▌      | 3530/10073 [00:14<00:18, 354.86article/s]
Chunking [llamaindex]:  35%|███▌      | 3568/10073 [00:14<00:18, 356.87article/s]
Chunking [llamaindex]:  36%|███▌      | 3604/10073 [00:14<00:18, 355.07article/s]
Chunking [llamaindex]:  36%|███▌      | 3646/10073 [00:15<00:17, 371.45article/s]
Chunking [llamaindex]:  37%|███▋      | 3684/10073 [00:15<00:17, 368.62article/s]
Chunking [llamaindex]:  37%|███▋      | 3721/10073 [00:15<00:17, 366.02article/s]
Chunking [llamaindex]:  37%|███▋      | 3763/10073 [00:15<00:16, 379.41article/s]
Chunking [llamaindex]:  38%|███▊      | 3801/10073 [00:15<00:16, 372.96article/s]
Chunking [llamaindex]:  38%|███▊      | 3839/10073 [00:15<00:17, 356.63article/s]
Chunking [llamaindex]:  38%|███▊      | 3875/10073 [00:15<00:17, 356.72article/s]
Chunking [llamaindex]:  39%|███▉      | 3914/10073 [00:15<00:16, 366.14article/s]
Chunking [llamaindex]:  39%|███▉      | 3954/10073 [00:15<00:16, 371.20article/s]
Chunking [llamaindex]:  40%|███▉      | 3992/10073 [00:16<00:17, 355.72article/s]
Chunking [llamaindex]:  40%|████      | 4031/10073 [00:16<00:16, 362.19article/s]
Chunking [llamaindex]:  40%|████      | 4068/10073 [00:16<00:16, 362.09article/s]
Chunking [llamaindex]:  41%|████      | 4105/10073 [00:16<00:16, 361.32article/s]
Chunking [llamaindex]:  41%|████      | 4142/10073 [00:16<00:16, 362.00article/s]
Chunking [llamaindex]:  41%|████▏     | 4179/10073 [00:16<00:16, 356.42article/s]
Chunking [llamaindex]:  42%|████▏     | 4216/10073 [00:16<00:16, 360.10article/s]
Chunking [llamaindex]:  42%|████▏     | 4253/10073 [00:16<00:16, 362.78article/s]
Chunking [llamaindex]:  43%|████▎     | 4291/10073 [00:16<00:15, 365.10article/s]
Chunking [llamaindex]:  43%|████▎     | 4328/10073 [00:16<00:16, 357.58article/s]
Chunking [llamaindex]:  43%|████▎     | 4364/10073 [00:17<00:16, 345.36article/s]
Chunking [llamaindex]:  44%|████▎     | 4399/10073 [00:17<00:16, 344.13article/s]
Chunking [llamaindex]:  44%|████▍     | 4439/10073 [00:17<00:15, 355.38article/s]
Chunking [llamaindex]:  44%|████▍     | 4475/10073 [00:17<00:16, 349.58article/s]
Chunking [llamaindex]:  45%|████▍     | 4511/10073 [00:17<00:16, 343.85article/s]
Chunking [llamaindex]:  45%|████▌     | 4554/10073 [00:17<00:15, 364.14article/s]
Chunking [llamaindex]:  46%|████▌     | 4591/10073 [00:17<00:15, 348.55article/s]
Chunking [llamaindex]:  46%|████▌     | 4631/10073 [00:17<00:15, 359.85article/s]
Chunking [llamaindex]:  46%|████▋     | 4671/10073 [00:17<00:14, 370.02article/s]
Chunking [llamaindex]:  47%|████▋     | 4709/10073 [00:18<00:15, 345.78article/s]
Chunking [llamaindex]:  47%|████▋     | 4744/10073 [00:18<00:17, 299.66article/s]
Chunking [llamaindex]:  47%|████▋     | 4776/10073 [00:18<00:19, 275.64article/s]
Chunking [llamaindex]:  48%|████▊     | 4805/10073 [00:18<00:19, 263.74article/s]
Chunking [llamaindex]:  48%|████▊     | 4833/10073 [00:18<00:20, 253.95article/s]
Chunking [llamaindex]:  48%|████▊     | 4859/10073 [00:18<00:21, 241.67article/s]
Chunking [llamaindex]:  48%|████▊     | 4884/10073 [00:18<00:21, 237.41article/s]
Chunking [llamaindex]:  49%|████▊     | 4909/10073 [00:18<00:21, 239.51article/s]
Chunking [llamaindex]:  49%|████▉     | 4934/10073 [00:19<00:21, 234.89article/s]
Chunking [llamaindex]:  49%|████▉     | 4958/10073 [00:19<00:22, 230.01article/s]
Chunking [llamaindex]:  49%|████▉     | 4982/10073 [00:19<00:22, 228.30article/s]
Chunking [llamaindex]:  50%|████▉     | 5005/10073 [00:19<00:23, 211.19article/s]
Chunking [llamaindex]:  50%|████▉     | 5027/10073 [00:19<00:24, 202.72article/s]
Chunking [llamaindex]:  50%|█████     | 5052/10073 [00:19<00:23, 212.72article/s]
Chunking [llamaindex]:  50%|█████     | 5076/10073 [00:19<00:22, 219.51article/s]
Chunking [llamaindex]:  51%|█████     | 5099/10073 [00:19<00:23, 215.89article/s]
Chunking [llamaindex]:  51%|█████     | 5123/10073 [00:19<00:22, 221.44article/s]
Chunking [llamaindex]:  51%|█████     | 5149/10073 [00:20<00:21, 230.12article/s]
Chunking [llamaindex]:  51%|█████▏    | 5173/10073 [00:20<00:22, 222.61article/s]
Chunking [llamaindex]:  52%|█████▏    | 5196/10073 [00:20<00:23, 208.22article/s]
Chunking [llamaindex]:  52%|█████▏    | 5221/10073 [00:20<00:22, 218.03article/s]
Chunking [llamaindex]:  52%|█████▏    | 5245/10073 [00:20<00:21, 223.96article/s]
Chunking [llamaindex]:  52%|█████▏    | 5281/10073 [00:20<00:18, 262.45article/s]
Chunking [llamaindex]:  53%|█████▎    | 5323/10073 [00:20<00:15, 307.34article/s]
Chunking [llamaindex]:  53%|█████▎    | 5361/10073 [00:20<00:14, 327.55article/s]
Chunking [llamaindex]:  54%|█████▎    | 5395/10073 [00:20<00:14, 323.77article/s]
Chunking [llamaindex]:  54%|█████▍    | 5428/10073 [00:21<00:14, 315.19article/s]
Chunking [llamaindex]:  54%|█████▍    | 5468/10073 [00:21<00:13, 337.93article/s]
Chunking [llamaindex]:  55%|█████▍    | 5503/10073 [00:21<00:13, 337.98article/s]
Chunking [llamaindex]:  55%|█████▍    | 5537/10073 [00:21<00:13, 330.77article/s]
Chunking [llamaindex]:  55%|█████▌    | 5575/10073 [00:21<00:13, 343.00article/s]
Chunking [llamaindex]:  56%|█████▌    | 5610/10073 [00:21<00:12, 344.32article/s]
Chunking [llamaindex]:  56%|█████▌    | 5645/10073 [00:21<00:12, 344.22article/s]
Chunking [llamaindex]:  56%|█████▋    | 5680/10073 [00:21<00:12, 343.78article/s]
Chunking [llamaindex]:  57%|█████▋    | 5718/10073 [00:21<00:12, 353.61article/s]
Chunking [llamaindex]:  57%|█████▋    | 5755/10073 [00:21<00:12, 355.12article/s]
Chunking [llamaindex]:  58%|█████▊    | 5794/10073 [00:22<00:11, 364.88article/s]
Chunking [llamaindex]:  58%|█████▊    | 5831/10073 [00:22<00:11, 360.92article/s]
Chunking [llamaindex]:  58%|█████▊    | 5869/10073 [00:22<00:11, 365.56article/s]
Chunking [llamaindex]:  59%|█████▊    | 5906/10073 [00:22<00:11, 347.84article/s]
Chunking [llamaindex]:  59%|█████▉    | 5943/10073 [00:22<00:11, 353.40article/s]
Chunking [llamaindex]:  59%|█████▉    | 5979/10073 [00:22<00:11, 342.55article/s]
Chunking [llamaindex]:  60%|█████▉    | 6018/10073 [00:22<00:11, 354.18article/s]
Chunking [llamaindex]:  60%|██████    | 6054/10073 [00:22<00:11, 345.63article/s]

'Starting chunking: 10073 article(s), 4 strategy(ies), output_dir=/content/Text-Mining---RAG-on-News/src/embed/output/chunks\n\nChunking [token]:   0%|          | 0/10073 [00:00<?, ?article/s]\nChunking [token]:   1%|          | 121/10073 [00:00<00:08, 1200.61article/s]\nChunking [token]:   2%|▏         | 242/10073 [00:00<00:08, 1093.33article/s]\nChunking [token]:   4%|▎         | 363/10073 [00:00<00:08, 1140.54article/s]\nChunking [token]:   5%|▍         | 494/10073 [00:00<00:07, 1199.17article/s]\nChunking [token]:   6%|▌         | 615/10073 [00:00<00:08, 1158.67article/s]\nChunking [token]:   7%|▋         | 744/10073 [00:00<00:07, 1196.78article/s]\nChunking [token]:   9%|▊         | 866/10073 [00:00<00:07, 1203.64article/s]\nChunking [token]:  10%|▉         | 987/10073 [00:00<00:07, 1198.63article/s]\nChunking [token]:  11%|█         | 1123/10073 [00:00<00:07, 1246.44article/s]\nChunking [token]:  12%|█▏        | 1248/10073 [00:01<00:07, 1188.55article/s]\nChunking [token]:  14%|█▍        | 1443/10073 [00:01<00:06, 1409.66article/s]\nChunking [token]:  17%|█▋        | 1665/10073 [00:01<00:05, 1646.43article/s]\nChunking [token]:  19%|█▊        | 1876/10073 [00:01<00:04, 1780.52article/s]\nChunking [token]:  21%|██        | 2089/10073 [00:01<00:04, 1884.22article/s]\nChunking [token]:  23%|██▎       | 2287/10073 [00:01<00:04, 1910.15article/s]\nChunking [token]:  25%|██▍       | 2479/10073 [00:01<00:04, 1888.84article/s]\nChunking [token]:  27%|██▋       | 2683/10073 [00:01<00:03, 1931.86article/s]\nChunking [token]:  29%|██▉       | 2902/10073 [00:01<00:03, 2007.32article/s]\nChunking [token]:  31%|███       | 3125/10073 [00:01<00:03, 2073.54article/s]\nChunking [token]:  33%|███▎      | 3344/10073 [00:02<00:03, 2107.01article/s]\nChunking [token]:  35%|███▌      | 3555/10073 [00:02<00:03, 2032.82article/s]\nChunking [token]:  38%|███▊      | 3785/10073 [00:02<00:02, 2110.12article/s]\nChunking [token]:  40%|███▉      | 3997/10073 [00:02<00:02, 2088.08article/s]\nChunking [token]:  42%|████▏     | 4213/10073 [00:02<00:02, 2108.04article/s]\nChunking [token]:  44%|████▍     | 4425/10073 [00:02<00:02, 2105.67article/s]\nChunking [token]:  46%|████▌     | 4636/10073 [00:02<00:02, 1998.64article/s]\nChunking [token]:  48%|████▊     | 4848/10073 [00:02<00:02, 2032.14article/s]\nChunking [token]:  50%|█████     | 5055/10073 [00:02<00:02, 2041.61article/s]\nChunking [token]:  52%|█████▏    | 5264/10073 [00:02<00:02, 2055.15article/s]\nChunking [token]:  54%|█████▍    | 5471/10073 [00:03<00:02, 2039.04article/s]\nChunking [token]:  56%|█████▋    | 5676/10073 [00:03<00:02, 2014.24article/s]\nChunking [token]:  58%|█████▊    | 5878/10073 [00:03<00:02, 1994.82article/s]\nChunking [token]:  60%|██████    | 6078/10073 [00:03<00:02, 1949.67article/s]\nChunking [token]:  62%|██████▏   | 6288/10073 [00:03<00:01, 1992.72article/s]\nChunking [token]:  65%|██████▍   | 6503/10073 [00:03<00:01, 2037.67article/s]\nChunking [token]:  67%|██████▋   | 6708/10073 [00:03<00:01, 2005.10article/s]\nChunking [token]:  69%|██████▉   | 6936/10073 [00:03<00:01, 2084.58article/s]\nChunking [token]:  71%|███████   | 7158/10073 [00:03<00:01, 2120.53article/s]\nChunking [token]:  73%|███████▎  | 7377/10073 [00:04<00:01, 2138.99article/s]\nChunking [token]:  75%|███████▌  | 7592/10073 [00:04<00:01, 2106.99article/s]\nChunking [token]:  77%|███████▋  | 7803/10073 [00:04<00:01, 2047.81article/s]\nChunking [token]:  80%|███████▉  | 8009/10073 [00:04<00:01, 1756.81article/s]\nChunking [token]:  82%|████████▏ | 8216/10073 [00:04<00:01, 1838.59article/s]\nChunking [token]:  84%|████████▎ | 8412/10073 [00:04<00:00, 1871.21article/s]\nChunking [token]:  86%|████████▌ | 8619/10073 [00:04<00:00, 1906.89article/s]\nChunking [token]:  88%|████████▊ | 8814/10073 [00:04<00:00, 1905.70article/s]\nChunking [token]:  89%|████████▉ | 9009/10073 [00:04<00:00, 1912.74article/s]\nChunking [token]:  92%|█████████▏| 9234/10073 [00:05<00:00, 2010.51article/s]\nChunking [token]:  94%|█████████▍| 9463/10073 [00:05<00:00, 2092.31article/s]\nChunking [token]:  96%|█████████▌| 9674/10073 [00:05<00:00, 2078.41article/s]\nChunking [token]:  98%|█████████▊| 9889/10073 [00:05<00:00, 2099.05article/s]\nChunking [token]: 100%|██████████| 10073/10073 [00:05<00:00, 1866.14article/s]\nCompleted token: 10073 article(s), 24099 chunk(s), 5.39781s -> /content/Text-Mining---RAG-on-News/src/embed/output/chunks/vieonline_news_chunks_token.jsonl\n{\n  "token": {\n    "output_path": "/content/Text-Mining---RAG-on-News/src/embed/output/chunks/vieonline_news_chunks_token.jsonl",\n    "config": {\n      "strategy": "token",\n      "chunk_size": 400,\n      "overlap": 80,\n      "min_chunk_tokens": 80,\n      "small_article_chars": 1000,\n      "max_chunks_per_article": null,\n      "inject_title_description": true\n    },\n    "stats": {\n      "articles_read": 10073,\n      "chunks_written": 24099,\n      "short_articles": 13,\n      "truncated_articles": 0,\n      "empty_articles": 0,\n      "total_chunk_tokens": 8034815,\n      "total_chunk_chars": 36876593,\n      "min_chunk_tokens": 50,\n      "max_chunk_tokens": 400,\n      "min_chunk_chars": 221,\n      "max_chunk_chars": 2869,\n      "elapsed_seconds": 5.39781,\n      "avg_chunks_per_article": 2.3924,\n      "avg_chunk_tokens": 333.4086,\n      "avg_chunk_chars": 1530.2126,\n      "chunks_per_second": 4464.5884\n    }\n  }\n}\n\nChunking [llamaindex]:   0%|          | 0/10073 [00:00<?, ?article/s]\nChunking [llamaindex]:   0%|          | 1/10073 [00:04<11:31:13,  4.12s/article]\nChunking [llamaindex]:   0%|          | 41/10073 [00:04<12:15, 13.64article/s]  \nChunking [llamaindex]:   1%|          | 76/10073 [00:04<05:45, 28.95article/s]\nChunking [llamaindex]:   1%|          | 118/10073 [00:04<03:08, 52.82article/s]\nChunking [llamaindex]:   2%|▏         | 152/10073 [00:04<02:11, 75.50article/s]\nChunking [llamaindex]:   2%|▏         | 189/10073 [00:04<01:33, 105.36article/s]\nChunking [llamaindex]:   2%|▏         | 225/10073 [00:04<01:11, 137.17article/s]\nChunking [llamaindex]:   3%|▎         | 260/10073 [00:04<00:58, 166.71article/s]\nChunking [llamaindex]:   3%|▎         | 295/10073 [00:04<00:49, 198.80article/s]\nChunking [llamaindex]:   3%|▎         | 334/10073 [00:05<00:41, 236.58article/s]\nChunking [llamaindex]:   4%|▎         | 372/10073 [00:05<00:36, 268.15article/s]\nChunking [llamaindex]:   4%|▍         | 409/10073 [00:05<00:33, 291.13article/s]\nChunking [llamaindex]:   4%|▍         | 446/10073 [00:05<00:31, 308.50article/s]\nChunking [llamaindex]:   5%|▍         | 482/10073 [00:05<00:29, 321.26article/s]\nChunking [llamaindex]:   5%|▌         | 518/10073 [00:05<00:31, 302.54article/s]\nChunking [llamaindex]:   5%|▌         | 552/10073 [00:05<00:33, 288.48article/s]\nChunking [llamaindex]:   6%|▌         | 583/10073 [00:05<00:35, 266.57article/s]\nChunking [llamaindex]:   6%|▌         | 612/10073 [00:05<00:36, 262.39article/s]\nChunking [llamaindex]:   6%|▋         | 640/10073 [00:06<00:39, 240.96article/s]\nChunking [llamaindex]:   7%|▋         | 666/10073 [00:06<00:38, 244.42article/s]\nChunking [llamaindex]:   7%|▋         | 692/10073 [00:06<00:40, 233.40article/s]\nChunking [llamaindex]:   7%|▋         | 718/10073 [00:06<00:39, 239.03article/s]\nChunking [llamaindex]:   7%|▋         | 744/10073 [00:06<00:38, 241.23article/s]\nChunking [llamaindex]:   8%|▊         | 769/10073 [00:06<00:39, 233.45article/s]\nChunking [llamaindex]:   8%|▊         | 793/10073 [00:06<00:39, 233.83article/s]\nChunking [llamaindex]:   8%|▊         | 819/10073 [00:06<00:38, 238.99article/s]\nChunking [llamaindex]:   8%|▊         | 844/10073 [00:07<00:40, 225.39article/s]\nChunking [llamaindex]:   9%|▊         | 868/10073 [00:07<00:40, 228.75article/s]\nChunking [llamaindex]:   9%|▉         | 892/10073 [00:07<00:40, 224.98article/s]\nChunking [llamaindex]:   9%|▉         | 915/10073 [00:07<00:41, 220.35article/s]\nChunking [llamaindex]:   9%|▉         | 941/10073 [00:07<00:40, 228.14article/s]\nChunking [llamaindex]:  10%|▉         | 965/10073 [00:07<00:40, 226.56article/s]\nChunking [llamaindex]:  10%|▉         | 990/10073 [00:07<00:39, 230.88article/s]\nChunking [llamaindex]:  10%|█         | 1014/10073 [00:07<00:39, 229.88article/s]\nChunking [llamaindex]:  10%|█         | 1038/10073 [00:07<00:39, 225.95article/s]\nChunking [llamaindex]:  11%|█         | 1061/10073 [00:07<00:40, 224.03article/s]\nChunking [llamaindex]:  11%|█         | 1090/10073 [00:08<00:37, 242.26article/s]\nChunking [llamaindex]:  11%|█         | 1125/10073 [00:08<00:32, 271.68article/s]\nChunking [llamaindex]:  12%|█▏        | 1161/10073 [00:08<00:30, 296.98article/s]\nChunking [llamaindex]:  12%|█▏        | 1199/10073 [00:08<00:27, 319.99article/s]\nChunking [llamaindex]:  12%|█▏        | 1232/10073 [00:08<00:27, 316.31article/s]\nChunking [llamaindex]:  13%|█▎        | 1268/10073 [00:08<00:26, 327.76article/s]\nChunking [llamaindex]:  13%|█▎        | 1304/10073 [00:08<00:26, 332.60article/s]\nChunking [llamaindex]:  13%|█▎        | 1338/10073 [00:08<00:26, 325.96article/s]\nChunking [llamaindex]:  14%|█▎        | 1378/10073 [00:08<00:25, 346.03article/s]\nChunking [llamaindex]:  14%|█▍        | 1414/10073 [00:08<00:25, 346.14article/s]\nChunking [llamaindex]:  14%|█▍        | 1456/10073 [00:09<00:23, 367.50article/s]\nChunking [llamaindex]:  15%|█▍        | 1498/10073 [00:09<00:22, 380.40article/s]\nChunking [llamaindex]:  15%|█▌        | 1539/10073 [00:09<00:21, 388.67article/s]\nChunking [llamaindex]:  16%|█▌        | 1578/10073 [00:09<00:22, 372.19article/s]\nChunking [llamaindex]:  16%|█▌        | 1616/10073 [00:09<00:22, 369.15article/s]\nChunking [llamaindex]:  16%|█▋        | 1654/10073 [00:09<00:22, 371.82article/s]\nChunking [llamaindex]:  17%|█▋        | 1692/10073 [00:09<00:24, 344.69article/s]\nChunking [llamaindex]:  17%|█▋        | 1727/10073 [00:09<00:24, 337.15article/s]\nChunking [llamaindex]:  18%|█▊        | 1766/10073 [00:09<00:23, 349.58article/s]\nChunking [llamaindex]:  18%|█▊        | 1807/10073 [00:10<00:22, 364.60article/s]\nChunking [llamaindex]:  18%|█▊        | 1848/10073 [00:10<00:21, 375.45article/s]\nChunking [llamaindex]:  19%|█▉        | 1889/10073 [00:10<00:21, 382.60article/s]\nChunking [llamaindex]:  19%|█▉        | 1928/10073 [00:10<00:22, 369.15article/s]\nChunking [llamaindex]:  20%|█▉        | 1966/10073 [00:10<00:21, 372.09article/s]\nChunking [llamaindex]:  20%|█▉        | 2004/10073 [00:10<00:22, 352.98article/s]\nChunking [llamaindex]:  20%|██        | 2040/10073 [00:10<00:22, 352.42article/s]\nChunking [llamaindex]:  21%|██        | 2079/10073 [00:10<00:22, 362.92article/s]\nChunking [llamaindex]:  21%|██        | 2116/10073 [00:10<00:21, 362.99article/s]\nChunking [llamaindex]:  21%|██▏       | 2154/10073 [00:11<00:21, 360.50article/s]\nChunking [llamaindex]:  22%|██▏       | 2191/10073 [00:11<00:22, 355.11article/s]\nChunking [llamaindex]:  22%|██▏       | 2234/10073 [00:11<00:21, 372.42article/s]\nChunking [llamaindex]:  23%|██▎       | 2274/10073 [00:11<00:20, 378.94article/s]\nChunking [llamaindex]:  23%|██▎       | 2312/10073 [00:11<00:21, 369.31article/s]\nChunking [llamaindex]:  23%|██▎       | 2352/10073 [00:11<00:20, 376.28article/s]\nChunking [llamaindex]:  24%|██▎       | 2390/10073 [00:11<00:21, 365.00article/s]\nChunking [llamaindex]:  24%|██▍       | 2431/10073 [00:11<00:20, 376.28article/s]\nChunking [llamaindex]:  25%|██▍       | 2469/10073 [00:11<00:20, 363.67article/s]\nChunking [llamaindex]:  25%|██▍       | 2511/10073 [00:11<00:19, 379.09article/s]\nChunking [llamaindex]:  25%|██▌       | 2550/10073 [00:12<00:20, 374.32article/s]\nChunking [llamaindex]:  26%|██▌       | 2588/10073 [00:12<00:20, 373.31article/s]\nChunking [llamaindex]:  26%|██▌       | 2626/10073 [00:12<00:19, 374.45article/s]\nChunking [llamaindex]:  26%|██▋       | 2664/10073 [00:12<00:21, 350.15article/s]\nChunking [llamaindex]:  27%|██▋       | 2702/10073 [00:12<00:20, 355.70article/s]\nChunking [llamaindex]:  27%|██▋       | 2744/10073 [00:12<00:19, 370.26article/s]\nChunking [llamaindex]:  28%|██▊       | 2783/10073 [00:12<00:19, 373.57article/s]\nChunking [llamaindex]:  28%|██▊       | 2828/10073 [00:12<00:18, 394.74article/s]\nChunking [llamaindex]:  28%|██▊       | 2868/10073 [00:12<00:21, 338.30article/s]\nChunking [llamaindex]:  29%|██▉       | 2904/10073 [00:13<00:21, 339.77article/s]\nChunking [llamaindex]:  29%|██▉       | 2949/10073 [00:13<00:19, 367.70article/s]\nChunking [llamaindex]:  30%|██▉       | 2987/10073 [00:13<00:19, 364.86article/s]\nChunking [llamaindex]:  30%|███       | 3025/10073 [00:13<00:19, 357.36article/s]\nChunking [llamaindex]:  30%|███       | 3067/10073 [00:13<00:18, 374.79article/s]\nChunking [llamaindex]:  31%|███       | 3105/10073 [00:13<00:18, 370.37article/s]\nChunking [llamaindex]:  31%|███       | 3143/10073 [00:13<00:18, 367.10article/s]\nChunking [llamaindex]:  32%|███▏      | 3183/10073 [00:13<00:18, 375.46article/s]\nChunking [llamaindex]:  32%|███▏      | 3224/10073 [00:13<00:17, 382.16article/s]\nChunking [llamaindex]:  32%|███▏      | 3263/10073 [00:14<00:18, 363.27article/s]\nChunking [llamaindex]:  33%|███▎      | 3300/10073 [00:14<00:19, 355.93article/s]\nChunking [llamaindex]:  33%|███▎      | 3340/10073 [00:14<00:18, 365.74article/s]\nChunking [llamaindex]:  34%|███▎      | 3377/10073 [00:14<00:19, 345.32article/s]\nChunking [llamaindex]:  34%|███▍      | 3415/10073 [00:14<00:18, 352.69article/s]\nChunking [llamaindex]:  34%|███▍      | 3455/10073 [00:14<00:18, 365.73article/s]\nChunking [llamaindex]:  35%|███▍      | 3493/10073 [00:14<00:17, 368.06article/s]\nChunking [llamaindex]:  35%|███▌      | 3530/10073 [00:14<00:18, 354.86article/s]\nChunking [llamaindex]:  35%|███▌      | 3568/10073 [00:14<00:18, 356.87article/s]\nChunking [llamaindex]:  36%|███▌      | 3604/10073 [00:14<00:18, 355.07article/s]\nChunking [llamaindex]:  36%|███▌      | 3646/10073 [00:15<00:17, 371.45article/s]\nChunking [llamaindex]:  37%|███▋      | 3684/10073 [00:15<00:17, 368.62article/s]\nChunking [llamaindex]:  37%|███▋      | 3721/10073 [00:15<00:17, 366.02article/s]\nChunking [llamaindex]:  37%|███▋      | 3763/10073 [00:15<00:16, 379.41article/s]\nChunking [llamaindex]:  38%|███▊      | 3801/10073 [00:15<00:16, 372.96article/s]\nChunking [llamaindex]:  38%|███▊      | 3839/10073 [00:15<00:17, 356.63article/s]\nChunking [llamaindex]:  38%|███▊      | 3875/10073 [00:15<00:17, 356.72article/s]\nChunking [llamaindex]:  39%|███▉      | 3914/10073 [00:15<00:16, 366.14article/s]\nChunking [llamaindex]:  39%|███▉      | 3954/10073 [00:15<00:16, 371.20article/s]\nChunking [llamaindex]:  40%|███▉      | 3992/10073 [00:16<00:17, 355.72article/s]\nChunking [llamaindex]:  40%|████      | 4031/10073 [00:16<00:16, 362.19article/s]\nChunking [llamaindex]:  40%|████      | 4068/10073 [00:16<00:16, 362.09article/s]\nChunking [llamaindex]:  41%|████      | 4105/10073 [00:16<00:16, 361.32article/s]\nChunking [llamaindex]:  41%|████      | 4142/10073 [00:16<00:16, 362.00article/s]\nChunking [llamaindex]:  41%|████▏     | 4179/10073 [00:16<00:16, 356.42article/s]\nChunking [llamaindex]:  42%|████▏     | 4216/10073 [00:16<00:16, 360.10article/s]\nChunking [llamaindex]:  42%|████▏     | 4253/10073 [00:16<00:16, 362.78article/s]\nChunking [llamaindex]:  43%|████▎     | 4291/10073 [00:16<00:15, 365.10article/s]\nChunking [llamaindex]:  43%|████▎     | 4328/10073 [00:16<00:16, 357.58article/s]\nChunking [llamaindex]:  43%|████▎     | 4364/10073 [00:17<00:16, 345.36article/s]\nChunking [llamaindex]:  44%|████▎     | 4399/10073 [00:17<00:16, 344.13article/s]\nChunking [llamaindex]:  44%|████▍     | 4439/10073 [00:17<00:15, 355.38article/s]\nChunking [llamaindex]:  44%|████▍     | 4475/10073 [00:17<00:16, 349.58article/s]\nChunking [llamaindex]:  45%|████▍     | 4511/10073 [00:17<00:16, 343.85article/s]\nChunking [llamaindex]:  45%|████▌     | 4554/10073 [00:17<00:15, 364.14article/s]\nChunking [llamaindex]:  46%|████▌     | 4591/10073 [00:17<00:15, 348.55article/s]\nChunking [llamaindex]:  46%|████▌     | 4631/10073 [00:17<00:15, 359.85article/s]\nChunking [llamaindex]:  46%|████▋     | 4671/10073 [00:17<00:14, 370.02article/s]\nChunking [llamaindex]:  47%|████▋     | 4709/10073 [00:18<00:15, 345.78article/s]\nChunking [llamaindex]:  47%|████▋     | 4744/10073 [00:18<00:17, 299.66article/s]\nChunking [llamaindex]:  47%|████▋     | 4776/10073 [00:18<00:19, 275.64article/s]\nChunking [llamaindex]:  48%|████▊     | 4805/10073 [00:18<00:19, 263.74article/s]\nChunking [llamaindex]:  48%|████▊     | 4833/10073 [00:18<00:20, 253.95article/s]\nChunking [llamaindex]:  48%|████▊     | 4859/10073 [00:18<00:21, 241.67article/s]\nChunking [llamaindex]:  48%|████▊     | 4884/10073 [00:18<00:21, 237.41article/s]\nChunking [llamaindex]:  49%|████▊     | 4909/10073 [00:18<00:21, 239.51article/s]\nChunking [llamaindex]:  49%|████▉     | 4934/10073 [00:19<00:21, 234.89article/s]\nChunking [llamaindex]:  49%|████▉     | 4958/10073 [00:19<00:22, 230.01article/s]\nChunking [llamaindex]:  49%|████▉     | 4982/10073 [00:19<00:22, 228.30article/s]\nChunking [llamaindex]:  50%|████▉     | 5005/10073 [00:19<00:23, 211.19article/s]\nChunking [llamaindex]:  50%|████▉     | 5027/10073 [00:19<00:24, 202.72article/s]\nChunking [llamaindex]:  50%|█████     | 5052/10073 [00:19<00:23, 212.72article/s]\nChunking [llamaindex]:  50%|█████     | 5076/10073 [00:19<00:22, 219.51article/s]\nChunking [llamaindex]:  51%|█████     | 5099/10073 [00:19<00:23, 215.89article/s]\nChunking [llamaindex]:  51%|█████     | 5123/10073 [00:19<00:22, 221.44article/s]\nChunking [llamaindex]:  51%|█████     | 5149/10073 [00:20<00:21, 230.12article/s]\nChunking [llamaindex]:  51%|█████▏    | 5173/10073 [00:20<00:22, 222.61article/s]\nChunking [llamaindex]:  52%|█████▏    | 5196/10073 [00:20<00:23, 208.22article/s]\nChunking [llamaindex]:  52%|█████▏    | 5221/10073 [00:20<00:22, 218.03article/s]\nChunking [llamaindex]:  52%|█████▏    | 5245/10073 [00:20<00:21, 223.96article/s]\nChunking [llamaindex]:  52%|█████▏    | 5281/10073 [00:20<00:18, 262.45article/s]\nChunking [llamaindex]:  53%|█████▎    | 5323/10073 [00:20<00:15, 307.34article/s]\nChunking [llamaindex]:  53%|█████▎    | 5361/10073 [00:20<00:14, 327.55article/s]\nChunking [llamaindex]:  54%|█████▎    | 5395/10073 [00:20<00:14, 323.77article/s]\nChunking [llamaindex]:  54%|█████▍    | 5428/10073 [00:21<00:14, 315.19article/s]\nChunking [llamaindex]:  54%|█████▍    | 5468/10073 [00:21<00:13, 337.93article/s]\nChunking [llamaindex]:  55%|█████▍    | 5503/10073 [00:21<00:13, 337.98article/s]\nChunking [llamaindex]:  55%|█████▍    | 5537/10073 [00:21<00:13, 330.77article/s]\nChunking [llamaindex]:  55%|█████▌    | 5575/10073 [00:21<00:13, 343.00article/s]\nChunking [llamaindex]:  56%|█████▌    | 5610/10073 [00:21<00:12, 344.32article/s]\nChunking [llamaindex]:  56%|█████▌    | 5645/10073 [00:21<00:12, 344.22article/s]\nChunking [llamaindex]:  56%|█████▋    | 5680/10073 [00:21<00:12, 343.78article/s]\nChunking [llamaindex]:  57%|█████▋    | 5718/10073 [00:21<00:12, 353.61article/s]\nChunking [llamaindex]:  57%|█████▋    | 5755/10073 [00:21<00:12, 355.12article/s]\nChunking [llamaindex]:  58%|█████▊    | 5794/10073 [00:22<00:11, 364.88article/s]\nChunking [llamaindex]:  58%|█████▊    | 5831/10073 [00:22<00:11, 360.92article/s]\nChunking [llamaindex]:  58%|█████▊    | 5869/10073 [00:22<00:11, 365.56article/s]\nChunking [llamaindex]:  59%|█████▊    | 5906/10073 [00:22<00:11, 347.84article/s]\nChunking [llamaindex]:  59%|█████▉    | 5943/10073 [00:22<00:11, 353.40article/s]\nChunking [llamaindex]:  59%|█████▉    | 5979/10073 [00:22<00:11, 342.55article/s]\nChunking [llamaindex]:  60%|█████▉    | 6018/10073 [00:22<00:11, 354.18article/s]\nChunking [llamaindex]:  60%|██████    | 6054/10073 [00:22<00:11, 345.63article/s]\nChunking [llamaindex]:  60%|██████    | 6089/10073 [00:22<00:11, 345.39article/s]\nChunking [llamaindex]:  61%|██████

## 5. Xem mẫu khác biệt input embedding giữa các strategy

In [10]:
chunk_files = [CHUNK_OUTPUT_DIR / f"vieonline_news_chunks_{strategy}.jsonl" for strategy in STRATEGIES]
compare_cmd = [
    sys.executable, "-m", "src.embed.compare_embedding_inputs",
    "--inputs", *chunk_files,
    "--sample-articles", 3,
    "--output", SAMPLE_REPORT,
]
run_cli(compare_cmd)
display(Markdown(SAMPLE_REPORT.read_text(encoding="utf-8")))

$ /usr/bin/python3 -m src.embed.compare_embedding_inputs --inputs /content/Text-Mining---RAG-on-News/src/embed/output/chunks/vieonline_news_chunks_token.jsonl /content/Text-Mining---RAG-on-News/src/embed/output/chunks/vieonline_news_chunks_llamaindex.jsonl /content/Text-Mining---RAG-on-News/src/embed/output/chunks/vieonline_news_chunks_structured.jsonl /content/Text-Mining---RAG-on-News/src/embed/output/chunks/vieonline_news_chunks_langchain_recursive.jsonl --sample-articles 3 --output /content/Text-Mining---RAG-on-News/src/embed/output/embedding_strategy_samples.md

{
  "output": "/content/Text-Mining---RAG-on-News/src/embed/output/embedding_strategy_samples.md"
}

[exit=0] elapsed=6.84s

# Embedding Strategy Samples

Report này so sánh text/metadata được đưa vào embedding giữa các chunking strategy cho cùng article.

## Article `10000`

### `token`

- Source: `/content/Text-Mining---RAG-on-News/src/embed/output/chunks/vieonline_news_chunks_token.jsonl`
- Num chunks: 3

| Chunk | Implementation | Structure | Tokens | Preview |
| ---: | --- | --- | ---: | --- |
| 0 | `internal_token_window` | `content` | 400 | Tiêu đề: Tom Cruise vẫn 'đặt cược' sinh mạng trong Mission: Impossible 8 Mô tả: Siêu sao hành động Tom Cruise vẫn miệt mài 'vào sinh ra tử' cùng vai diễn, suýt chết nhiều lần khi đóng phim Mission: Impossible - The Fi... |
| 1 | `internal_token_window` | `content` | 400 | Tiêu đề: Tom Cruise vẫn 'đặt cược' sinh mạng trong Mission: Impossible 8 Mô tả: Siêu sao hành động Tom Cruise vẫn miệt mài 'vào sinh ra tử' cùng vai diễn, suýt chết nhiều lần khi đóng phim Mission: Impossible - The Fi... |
| 2 | `internal_token_window` | `content` | 82 | Tiêu đề: Tom Cruise vẫn 'đặt cược' sinh mạng trong Mission: Impossible 8 Mô tả: Siêu sao hành động Tom Cruise vẫn miệt mài 'vào sinh ra tử' cùng vai diễn, suýt chết nhiều lần khi đóng phim Mission: Impossible - The Fi... |

### `llamaindex`

- Source: `/content/Text-Mining---RAG-on-News/src/embed/output/chunks/vieonline_news_chunks_llamaindex.jsonl`
- Num chunks: 4

| Chunk | Implementation | Structure | Tokens | Preview |
| ---: | --- | --- | ---: | --- |
| 0 | `llama_index.core.node_parser.SentenceSplitter` | `content` | 169 | Tiêu đề: Tom Cruise vẫn 'đặt cược' sinh mạng trong Mission: Impossible 8 Mô tả: Siêu sao hành động Tom Cruise vẫn miệt mài 'vào sinh ra tử' cùng vai diễn, suýt chết nhiều lần khi đóng phim Mission: Impossible - The Fi... |
| 1 | `llama_index.core.node_parser.SentenceSplitter` | `content` | 176 | Tiêu đề: Tom Cruise vẫn 'đặt cược' sinh mạng trong Mission: Impossible 8 Mô tả: Siêu sao hành động Tom Cruise vẫn miệt mài 'vào sinh ra tử' cùng vai diễn, suýt chết nhiều lần khi đóng phim Mission: Impossible - The Fi... |
| 2 | `llama_index.core.node_parser.SentenceSplitter` | `content` | 180 | Tiêu đề: Tom Cruise vẫn 'đặt cược' sinh mạng trong Mission: Impossible 8 Mô tả: Siêu sao hành động Tom Cruise vẫn miệt mài 'vào sinh ra tử' cùng vai diễn, suýt chết nhiều lần khi đóng phim Mission: Impossible - The Fi... |
| 3 | `llama_index.core.node_parser.SentenceSplitter` | `content` | 245 | Tiêu đề: Tom Cruise vẫn 'đặt cược' sinh mạng trong Mission: Impossible 8 Mô tả: Siêu sao hành động Tom Cruise vẫn miệt mài 'vào sinh ra tử' cùng vai diễn, suýt chết nhiều lần khi đóng phim Mission: Impossible - The Fi... |

### `structured`

- Source: `/content/Text-Mining---RAG-on-News/src/embed/output/chunks/vieonline_news_chunks_structured.jsonl`
- Num chunks: 3

| Chunk | Implementation | Structure | Tokens | Preview |
| ---: | --- | --- | ---: | --- |
| 0 | `internal_structured_sentence_window` | `content` | 369 | Tiêu đề: Tom Cruise vẫn 'đặt cược' sinh mạng trong Mission: Impossible 8 Mô tả: Siêu sao hành động Tom Cruise vẫn miệt mài 'vào sinh ra tử' cùng vai diễn, suýt chết nhiều lần khi đóng phim Mission: Impossible - The Fi... |
| 1 | `internal_structured_sentence_window` | `content` | 360 | Tiêu đề: Tom Cruise vẫn 'đặt cược' sinh mạng trong Mission: Impossible 8 Mô tả: Siêu sao hành động Tom Cruise vẫn miệt mài 'vào sinh ra tử' cùng vai diễn, suýt chết nhiều lần khi đóng phim Mission: Impossible - The Fi... |
| 2 | `internal_structured_sentence_window` | `content` | 245 | Tiêu đề: Tom Cruise vẫn 'đặt cược' sinh mạng trong Mission: Impossible 8 Mô tả: Siêu sao hành động Tom Cruise vẫn miệt mài 'vào sinh ra tử' cùng vai diễn, suýt chết nhiều lần khi đóng phim Mission: Impossible - The Fi... |

### `langchain_recursive`

- Source: `/content/Text-Mining---RAG-on-News/src/embed/output/chunks/vieonline_news_chunks_langchain_recursive.jsonl`
- Num chunks: 13

| Chunk | Implementation | Structure | Tokens | Preview |
| ---: | --- | --- | ---: | --- |
| 0 | `langchain_text_splitters.RecursiveCharacterTextSplitter` | `content` | 73 | Tiêu đề: Tom Cruise vẫn 'đặt cược' sinh mạng trong Mission: Impossible 8 Mô tả: Siêu sao hành động Tom Cruise vẫn miệt mài 'vào sinh ra tử' cùng vai diễn, suýt chết nhiều lần khi đóng phim Mission: Impossible - The Fi... |
| 1 | `langchain_text_splitters.RecursiveCharacterTextSplitter` | `content` | 24 | Tiêu đề: Tom Cruise vẫn 'đặt cược' sinh mạng trong Mission: Impossible 8 Mô tả: Siêu sao hành động Tom Cruise vẫn miệt mài 'vào sinh ra tử' cùng vai diễn, suýt chết nhiều lần khi đóng phim Mission: Impossible - The Fi... |
| 2 | `langchain_text_splitters.RecursiveCharacterTextSplitter` | `content` | 61 | Tiêu đề: Tom Cruise vẫn 'đặt cược' sinh mạng trong Mission: Impossible 8 Mô tả: Siêu sao hành động Tom Cruise vẫn miệt mài 'vào sinh ra tử' cùng vai diễn, suýt chết nhiều lần khi đóng phim Mission: Impossible - The Fi... |
| 3 | `langchain_text_splitters.RecursiveCharacterTextSplitter` | `content` | 56 | Tiêu đề: Tom Cruise vẫn 'đặt cược' sinh mạng trong Mission: Impossible 8 Mô tả: Siêu sao hành động Tom Cruise vẫn miệt mài 'vào sinh ra tử' cùng vai diễn, suýt chết nhiều lần khi đóng phim Mission: Impossible - The Fi... |
| 4 | `langchain_text_splitters.RecursiveCharacterTextSplitter` | `content` | 46 | Tiêu đề: Tom Cruise vẫn 'đặt cược' sinh mạng trong Mission: Impossible 8 Mô tả: Siêu sao hành động Tom Cruise vẫn miệt mài 'vào sinh ra tử' cùng vai diễn, suýt chết nhiều lần khi đóng phim Mission: Impossible - The Fi... |

## Article `100056`

### `token`

- Source: `/content/Text-Mining---RAG-on-News/src/embed/output/chunks/vieonline_news_chunks_token.jsonl`
- Num chunks: 5

| Chunk | Implementation | Structure | Tokens | Preview |
| ---: | --- | --- | ---: | --- |
| 0 | `internal_token_window` | `content` | 400 | Tiêu đề: Sắp xếp, sáp nhập trường ĐH: Quyền lợi của người lao động, sinh viên ra sao? Mô tả: Theo các chuyên gia, nhiều vấn đề đặt ra cần giải quyết khi xây dựng đề án sáp nhập các trường đại học như: nhân sự, cơ sở v... |
| 1 | `internal_token_window` | `content` | 400 | Tiêu đề: Sắp xếp, sáp nhập trường ĐH: Quyền lợi của người lao động, sinh viên ra sao? Mô tả: Theo các chuyên gia, nhiều vấn đề đặt ra cần giải quyết khi xây dựng đề án sáp nhập các trường đại học như: nhân sự, cơ sở v... |
| 2 | `internal_token_window` | `content` | 400 | Tiêu đề: Sắp xếp, sáp nhập trường ĐH: Quyền lợi của người lao động, sinh viên ra sao? Mô tả: Theo các chuyên gia, nhiều vấn đề đặt ra cần giải quyết khi xây dựng đề án sáp nhập các trường đại học như: nhân sự, cơ sở v... |
| 3 | `internal_token_window` | `content` | 400 | Tiêu đề: Sắp xếp, sáp nhập trường ĐH: Quyền lợi của người lao động, sinh viên ra sao? Mô tả: Theo các chuyên gia, nhiều vấn đề đặt ra cần giải quyết khi xây dựng đề án sáp nhập các trường đại học như: nhân sự, cơ sở v... |
| 4 | `internal_token_window` | `content` | 370 | Tiêu đề: Sắp xếp, sáp nhập trường ĐH: Quyền lợi của người lao động, sinh viên ra sao? Mô tả: Theo các chuyên gia, nhiều vấn đề đặt ra cần giải quyết khi xây dựng đề án sáp nhập các trường đại học như: nhân sự, cơ sở v... |

### `llamaindex`

- Source: `/content/Text-Mining---RAG-on-News/src/embed/output/chunks/vieonline_news_chunks_llamaindex.jsonl`
- Num chunks: 11

| Chunk | Implementation | Structure | Tokens | Preview |
| ---: | --- | --- | ---: | --- |
| 0 | `llama_index.core.node_parser.SentenceSplitter` | `content` | 154 | Tiêu đề: Sắp xếp, sáp nhập trường ĐH: Quyền lợi của người lao động, sinh viên ra sao? Mô tả: Theo các chuyên gia, nhiều vấn đề đặt ra cần giải quyết khi xây dựng đề án sáp nhập các trường đại học như: nhân sự, cơ sở v... |
| 1 | `llama_index.core.node_parser.SentenceSplitter` | `content` | 166 | Tiêu đề: Sắp xếp, sáp nhập trường ĐH: Quyền lợi của người lao động, sinh viên ra sao? Mô tả: Theo các chuyên gia, nhiều vấn đề đặt ra cần giải quyết khi xây dựng đề án sáp nhập các trường đại học như: nhân sự, cơ sở v... |
| 2 | `llama_index.core.node_parser.SentenceSplitter` | `content` | 181 | Tiêu đề: Sắp xếp, sáp nhập trường ĐH: Quyền lợi của người lao động, sinh viên ra sao? Mô tả: Theo các chuyên gia, nhiều vấn đề đặt ra cần giải quyết khi xây dựng đề án sáp nhập các trường đại học như: nhân sự, cơ sở v... |
| 3 | `llama_index.core.node_parser.SentenceSplitter` | `content` | 151 | Tiêu đề: Sắp xếp, sáp nhập trường ĐH: Quyền lợi của người lao động, sinh viên ra sao? Mô tả: Theo các chuyên gia, nhiều vấn đề đặt ra cần giải quyết khi xây dựng đề án sáp nhập các trường đại học như: nhân sự, cơ sở v... |
| 4 | `llama_index.core.node_parser.SentenceSplitter` | `content` | 180 | Tiêu đề: Sắp xếp, sáp nhập trường ĐH: Quyền lợi của người lao động, sinh viên ra sao? Mô tả: Theo các chuyên gia, nhiều vấn đề đặt ra cần giải quyết khi xây dựng đề án sáp nhập các trường đại học như: nhân sự, cơ sở v... |

### `structured`

- Source: `/content/Text-Mining---RAG-on-News/src/embed/output/chunks/vieonline_news_chunks_structured.jsonl`
- Num chunks: 6

| Chunk | Implementation | Structure | Tokens | Preview |
| ---: | --- | --- | ---: | --- |
| 0 | `internal_structured_sentence_window` | `content` | 379 | Tiêu đề: Sắp xếp, sáp nhập trường ĐH: Quyền lợi của người lao động, sinh viên ra sao? Mô tả: Theo các chuyên gia, nhiều vấn đề đặt ra cần giải quyết khi xây dựng đề án sáp nhập các trường đại học như: nhân sự, cơ sở v... |
| 1 | `internal_structured_sentence_window` | `content` | 381 | Tiêu đề: Sắp xếp, sáp nhập trường ĐH: Quyền lợi của người lao động, sinh viên ra sao? Mô tả: Theo các chuyên gia, nhiều vấn đề đặt ra cần giải quyết khi xây dựng đề án sáp nhập các trường đại học như: nhân sự, cơ sở v... |
| 2 | `internal_structured_sentence_window` | `content` | 386 | Tiêu đề: Sắp xếp, sáp nhập trường ĐH: Quyền lợi của người lao động, sinh viên ra sao? Mô tả: Theo các chuyên gia, nhiều vấn đề đặt ra cần giải quyết khi xây dựng đề án sáp nhập các trường đại học như: nhân sự, cơ sở v... |
| 3 | `internal_structured_sentence_window` | `content` | 372 | Tiêu đề: Sắp xếp, sáp nhập trường ĐH: Quyền lợi của người lao động, sinh viên ra sao? Mô tả: Theo các chuyên gia, nhiều vấn đề đặt ra cần giải quyết khi xây dựng đề án sáp nhập các trường đại học như: nhân sự, cơ sở v... |
| 4 | `internal_structured_sentence_window` | `content` | 388 | Tiêu đề: Sắp xếp, sáp nhập trường ĐH: Quyền lợi của người lao động, sinh viên ra sao? Mô tả: Theo các chuyên gia, nhiều vấn đề đặt ra cần giải quyết khi xây dựng đề án sáp nhập các trường đại học như: nhân sự, cơ sở v... |

### `langchain_recursive`

- Source: `/content/Text-Mining---RAG-on-News/src/embed/output/chunks/vieonline_news_chunks_langchain_recursive.jsonl`
- Num chunks: 24

| Chunk | Implementation | Structure | Tokens | Preview |
| ---: | --- | --- | ---: | --- |
| 0 | `langchain_text_splitters.RecursiveCharacterTextSplitter` | `content` | 65 | Tiêu đề: Sắp xếp, sáp nhập trường ĐH: Quyền lợi của người lao động, sinh viên ra sao? Mô tả: Theo các chuyên gia, nhiều vấn đề đặt ra cần giải quyết khi xây dựng đề án sáp nhập các trường đại học như: nhân sự, cơ sở v... |
| 1 | `langchain_text_splitters.RecursiveCharacterTextSplitter` | `content` | 63 | Tiêu đề: Sắp xếp, sáp nhập trường ĐH: Quyền lợi của người lao động, sinh viên ra sao? Mô tả: Theo các chuyên gia, nhiều vấn đề đặt ra cần giải quyết khi xây dựng đề án sáp nhập các trường đại học như: nhân sự, cơ sở v... |
| 2 | `langchain_text_splitters.RecursiveCharacterTextSplitter` | `content` | 47 | Tiêu đề: Sắp xếp, sáp nhập trường ĐH: Quyền lợi của người lao động, sinh viên ra sao? Mô tả: Theo các chuyên gia, nhiều vấn đề đặt ra cần giải quyết khi xây dựng đề án sáp nhập các trường đại học như: nhân sự, cơ sở v... |
| 3 | `langchain_text_splitters.RecursiveCharacterTextSplitter` | `content` | 65 | Tiêu đề: Sắp xếp, sáp nhập trường ĐH: Quyền lợi của người lao động, sinh viên ra sao? Mô tả: Theo các chuyên gia, nhiều vấn đề đặt ra cần giải quyết khi xây dựng đề án sáp nhập các trường đại học như: nhân sự, cơ sở v... |
| 4 | `langchain_text_splitters.RecursiveCharacterTextSplitter` | `content` | 74 | Tiêu đề: Sắp xếp, sáp nhập trường ĐH: Quyền lợi của người lao động, sinh viên ra sao? Mô tả: Theo các chuyên gia, nhiều vấn đề đặt ra cần giải quyết khi xây dựng đề án sáp nhập các trường đại học như: nhân sự, cơ sở v... |

## Article `10007`

### `token`

- Source: `/content/Text-Mining---RAG-on-News/src/embed/output/chunks/vieonline_news_chunks_token.jsonl`
- Num chunks: 2

| Chunk | Implementation | Structure | Tokens | Preview |
| ---: | --- | --- | ---: | --- |
| 0 | `internal_token_window` | `content` | 400 | Tiêu đề: Bandai quyết tâm đưa Gundam lên màn ảnh rộng Mô tả: Sau nhiều năm gián đoạn, dự án phim Gundam live-action cuối cùng cũng chính thức sản xuất. Chuyên mục: Giải trí Đoạn nội dung: Những phác thảo ban đầu của d... |
| 1 | `internal_token_window` | `content` | 249 | Tiêu đề: Bandai quyết tâm đưa Gundam lên màn ảnh rộng Mô tả: Sau nhiều năm gián đoạn, dự án phim Gundam live-action cuối cùng cũng chính thức sản xuất. Chuyên mục: Giải trí Đoạn nội dung: tại Bắc Mỹ thông qua anime, p... |

### `llamaindex`

- Source: `/content/Text-Mining---RAG-on-News/src/embed/output/chunks/vieonline_news_chunks_llamaindex.jsonl`
- Num chunks: 4

| Chunk | Implementation | Structure | Tokens | Preview |
| ---: | --- | --- | ---: | --- |
| 0 | `llama_index.core.node_parser.SentenceSplitter` | `content` | 166 | Tiêu đề: Bandai quyết tâm đưa Gundam lên màn ảnh rộng Mô tả: Sau nhiều năm gián đoạn, dự án phim Gundam live-action cuối cùng cũng chính thức sản xuất. Chuyên mục: Giải trí Đoạn nội dung: Những phác thảo ban đầu của d... |
| 1 | `llama_index.core.node_parser.SentenceSplitter` | `content` | 121 | Tiêu đề: Bandai quyết tâm đưa Gundam lên màn ảnh rộng Mô tả: Sau nhiều năm gián đoạn, dự án phim Gundam live-action cuối cùng cũng chính thức sản xuất. Chuyên mục: Giải trí Đoạn nội dung: Universal Century là điểm khở... |
| 2 | `llama_index.core.node_parser.SentenceSplitter` | `content` | 175 | Tiêu đề: Bandai quyết tâm đưa Gundam lên màn ảnh rộng Mô tả: Sau nhiều năm gián đoạn, dự án phim Gundam live-action cuối cùng cũng chính thức sản xuất. Chuyên mục: Giải trí Đoạn nội dung: Legendary Entertainmentcũng t... |
| 3 | `llama_index.core.node_parser.SentenceSplitter` | `content` | 140 | Tiêu đề: Bandai quyết tâm đưa Gundam lên màn ảnh rộng Mô tả: Sau nhiều năm gián đoạn, dự án phim Gundam live-action cuối cùng cũng chính thức sản xuất. Chuyên mục: Giải trí Đoạn nội dung: Tất cả đều khởi đầu từ animeM... |

### `structured`

- Source: `/content/Text-Mining---RAG-on-News/src/embed/output/chunks/vieonline_news_chunks_structured.jsonl`
- Num chunks: 2

| Chunk | Implementation | Structure | Tokens | Preview |
| ---: | --- | --- | ---: | --- |
| 0 | `internal_structured_sentence_window` | `content` | 385 | Tiêu đề: Bandai quyết tâm đưa Gundam lên màn ảnh rộng Mô tả: Sau nhiều năm gián đoạn, dự án phim Gundam live-action cuối cùng cũng chính thức sản xuất. Chuyên mục: Giải trí Đoạn nội dung: Những phác thảo ban đầu của d... |
| 1 | `internal_structured_sentence_window` | `content` | 283 | Tiêu đề: Bandai quyết tâm đưa Gundam lên màn ảnh rộng Mô tả: Sau nhiều năm gián đoạn, dự án phim Gundam live-action cuối cùng cũng chính thức sản xuất. Chuyên mục: Giải trí Đoạn nội dung: "Ông lớn" của ngành giải trí... |

### `langchain_recursive`

- Source: `/content/Text-Mining---RAG-on-News/src/embed/output/chunks/vieonline_news_chunks_langchain_recursive.jsonl`
- Num chunks: 9

| Chunk | Implementation | Structure | Tokens | Preview |
| ---: | --- | --- | ---: | --- |
| 0 | `langchain_text_splitters.RecursiveCharacterTextSplitter` | `content` | 64 | Tiêu đề: Bandai quyết tâm đưa Gundam lên màn ảnh rộng Mô tả: Sau nhiều năm gián đoạn, dự án phim Gundam live-action cuối cùng cũng chính thức sản xuất. Chuyên mục: Giải trí Đoạn nội dung: Những phác thảo ban đầu của d... |
| 1 | `langchain_text_splitters.RecursiveCharacterTextSplitter` | `content` | 56 | Tiêu đề: Bandai quyết tâm đưa Gundam lên màn ảnh rộng Mô tả: Sau nhiều năm gián đoạn, dự án phim Gundam live-action cuối cùng cũng chính thức sản xuất. Chuyên mục: Giải trí Đoạn nội dung: . Đây là một trong những sự k... |
| 2 | `langchain_text_splitters.RecursiveCharacterTextSplitter` | `content` | 48 | Tiêu đề: Bandai quyết tâm đưa Gundam lên màn ảnh rộng Mô tả: Sau nhiều năm gián đoạn, dự án phim Gundam live-action cuối cùng cũng chính thức sản xuất. Chuyên mục: Giải trí Đoạn nội dung: . Tuy chưa có nhiều chi tiết... |
| 3 | `langchain_text_splitters.RecursiveCharacterTextSplitter` | `content` | 63 | Tiêu đề: Bandai quyết tâm đưa Gundam lên màn ảnh rộng Mô tả: Sau nhiều năm gián đoạn, dự án phim Gundam live-action cuối cùng cũng chính thức sản xuất. Chuyên mục: Giải trí Đoạn nội dung: . Universal Century là điểm k... |
| 4 | `langchain_text_splitters.RecursiveCharacterTextSplitter` | `content` | 60 | Tiêu đề: Bandai quyết tâm đưa Gundam lên màn ảnh rộng Mô tả: Sau nhiều năm gián đoạn, dự án phim Gundam live-action cuối cùng cũng chính thức sản xuất. Chuyên mục: Giải trí Đoạn nội dung: . Tuy nhiên, với thông báo mớ... |

## 6. Embed từng strategy và quan sát tiến độ

Cell này là bước chậm nhất trên CPU. `tqdm` sẽ hiển thị tiến độ theo batch. Nếu quá chậm, giảm `ARTICLE_LIMIT`, giảm số `STRATEGIES`, hoặc giữ `BATCH_SIZE=4`.

In [11]:
for strategy, chunk_file in zip(STRATEGIES, chunk_files):
    output_dir = DENSE_OUTPUT_ROOT / strategy
    embed_cmd = [
        sys.executable, "-m", "src.embed.embed_chunks",
        "--input", chunk_file,
        "--output-dir", output_dir,
        "--model", MODEL_NAME,
        "--batch-size", BATCH_SIZE,
        "--sample-size", SAMPLE_SIZE,
        "--show-samples",
    ]
    run_cli(embed_cmd)

$ /usr/bin/python3 -m src.embed.embed_chunks --input /content/Text-Mining---RAG-on-News/src/embed/output/chunks/vieonline_news_chunks_token.jsonl --output-dir /content/Text-Mining---RAG-on-News/src/embed/output/dense/token --model intfloat/multilingual-e5-large --batch-size 4 --sample-size 5 --show-samples


Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]
Loading weights: 100%|██████████| 391/391 [00:00<00:00, 21883.23it/s]

Embedding:   0%|          | 0/6025 [00:00<?, ?batch/s]
Embedding:   0%|          | 1/6025 [00:00<1:40:12,  1.00batch/s]
Embedding:   0%|          | 2/6025 [00:01<1:01:57,  1.62batch/s]
Embedding:   0%|          | 3/6025 [00:01<49:59,  2.01batch/s]
Embedding:   0%|          | 4/6025 [00:02<44:14,  2.27batch/s]
Embedding:   0%|          | 5/6025 [00:02<41:00,  2.45batch/s]
Embedding:   0%|          | 6/6025 [00:02<39:09,  2.56batch/s]
Embedding:   0%|          | 7/6025 [00:03<38:11,  2.63batch/s]
Embedding:   0%|          | 8/6025 [00:03<37:33,  2.67batch/s]
Embedding:   0%|          | 9/6025 [00:03<37:10,  2.70batch/s]
Embedding:   0%|          | 10/6025 [00:04<36:55,  2.72batch/s]
Embedding:   0%|          | 11/6025 [00:04<36:39,  2.73batch/s]
Embedding:   0%|          | 12/6025 [00:04<36:39,  2.73batch/s]
Embedding:   0%|          | 13/6025 [00:05<36:24,  2.75batch/s]
Embedding:   0%|          | 14/6025 [00:05<36:09,  2.77batch/s]
Embedding:   0%|          | 15/6025 [00:06<36:00,  2.78batch/s]
Embedding:   0%|          | 16/6025 [00:06<35:46,  2.80batch/s]
Embedding:   0%|          | 17/6025 [00:06<35:43,  2.80batch/s]
Embedding:   0%|          | 18/6025 [00:07<35:41,  2.81batch/s]
Embedding:   0%|          | 19/6025 [00:07<35:34,  2.81batch/s]
Embedding:   0%|          | 20/6025 [00:07<35:45,  2.80batch/s]
Embedding:   0%|          | 21/6025 [00:08<35:47,  2.80batch/s]
Embedding:   0%|          | 22/6025 [00:08<35:42,  2.80batch/s]
Embedding:   0%|          | 23/6025 [00:08<35:45,  2.80batch/s]
Embedding:   0%|          | 24/6025 [00:09<35:51,  2.79batch/s]
Embedding:   0%|          | 25/6025 [00:09<35:39,  2.80batch/s]
Embedding:   0%|          | 26/6025 [00:09<35:48,  2.79batch/s]
Embedding:   0%|          | 27/6025 [00:10<35:48,  2.79batch/s]
Embedding:   0%|          | 28/6025 [00:10<36:05,  2.77batch/s]
Embedding:   0%|          | 29/6025 [00:11<36:01,  2.77batch/s]
Embedding:   0%|          | 30/6025 [00:11<35:59,  2.78batch/s]
Embedding:   1%|          | 31/6025 [00:11<35:58,  2.78batch/s]
Embedding:   1%|          | 32/6025 [00:12<35:55,  2.78batch/s]
Embedding:   1%|          | 33/6025 [00:12<35:50,  2.79batch/s]
Embedding:   1%|          | 34/6025 [00:12<35:54,  2.78batch/s]
Embedding:   1%|          | 35/6025 [00:13<35:54,  2.78batch/s]
Embedding:   1%|          | 36/6025 [00:13<35:57,  2.78batch/s]
Embedding:   1%|          | 37/6025 [00:13<35:53,  2.78batch/s]
Embedding:   1%|          | 38/6025 [00:14<35:56,  2.78batch/s]
Embedding:   1%|          | 39/6025 [00:14<36:00,  2.77batch/s]
Embedding:   1%|          | 40/6025 [00:14<36:10,  2.76batch/s]
Embedding:   1%|          | 41/6025 [00:15<36:07,  2.76batch/s]
Embedding:   1%|          | 42/6025 [00:15<36:14,  2.75batch/s]
Embedding:   1%|          | 43/6025 [00:16<36:17,  2.75batch/s]
Embedding:   1%|          | 44/6025 [00:16<36:27,  2.73batch/s]
Embedding:   1%|          | 45/6025 [00:16<36:31,  2.73batch/s]
Embedding:   1%|          | 46/6025 [00:17<36:38,  2.72batch/s]
Embedding:   1%|          | 47/6025 [00:17<36:43,  2.71batch/s]
Embedding:   1%|          | 48/6025 [00:17<36:31,  2.73batch/s]
Embedding:   1%|          | 49/6025 [00:18<36:22,  2.74batch/s]
Embedding:   1%|          | 50/6025 [00:18<36:17,  2.74batch/s]
Embedding:   1%|          | 51/6025 [00:19<36:17,  2.74batch/s]
Embedding:   1%|          | 52/6025 [00:19<36:18,  2.74batch/s]
Embedding:   1%|          | 53/6025 [00:19<36:15,  2.74batch/s]
Embedding:   1%|          | 54/6025 [00:20<36:25,  2.73batch/s]
Embedding:   1%|          | 55/6025 [00:20<36:25,  2.73batch/s]
Embedding:   1%|          | 56/6025 [00:20<36:24,  2.73batch/s]
Embedding:   1%|          | 57/6025 [00:21<36:25,  2.73batch/s]
Embedding:   1%|          | 58/6025 [00:21<36:19,  2.74batch/s]
Embedding:   1%|          | 59/6025 [00:21<36:22,  2.73batch/s]
Embedding:   1%|          | 60/6025 [00:22<36:21,  2.73batch/s]
Embedding:   1%|          | 61/6025 [00:22<36:17,  2.74batch/s]
Embedding:   1%|          | 62/6025 [00:23<36:11,  2.75batch/s]
Embedding:   1%|          | 63/6025 [00:23<36:14,  2.74batch/s]
Embedding:   1%|          | 64/6025 [00:23<36:16,  2.74batch/s]
Embedding:   1%|          | 65/6025 [00:24<36:16,  2.74batch/s]
Embedding:   1%|          | 66/6025 [00:24<36:24,  2.73batch/s]
Embedding:   1%|          | 67/6025 [00:24<36:32,  2.72batch/s]
Embedding:   1%|          | 68/6025 [00:25<36:33,  2.72batch/s]
Embedding:   1%|          | 69/6025 [00:25<36:33,  2.72batch/s]
Embedding:   1%|          | 70/6025 [00:25<36:36,  2.71batch/s]
Embedding:   1%|          | 71/6025 [00:26<36:31,  2.72batch/s]
Embedding:   1%|          | 72/6025 [00:26<36:46,  2.70batch/s]
Embedding:   1%|          | 73/6025 [00:27<36:41,  2.70batch/s]
Embedding:   1%|          | 74/6025 [00:27<36:40,  2.70batch/s]
Embedding:   1%|          | 75/6025 [00:27<36:56,  2.68batch/s]
Embedding:   1%|▏         | 76/6025 [00:28<36:58,  2.68batch/s]
Embedding:   1%|▏         | 77/6025 [00:28<37:10,  2.67batch/s]
Embedding:   1%|▏         | 78/6025 [00:28<37:17,  2.66batch/s]
Embedding:   1%|▏         | 79/6025 [00:29<37:22,  2.65batch/s]
Embedding:   1%|▏         | 80/6025 [00:29<37:26,  2.65batch/s]
Embedding:   1%|▏         | 81/6025 [00:30<37:34,  2.64batch/s]
Embedding:   1%|▏         | 82/6025 [00:30<37:19,  2.65batch/s]
Embedding:   1%|▏         | 83/6025 [00:30<37:11,  2.66batch/s]
Embedding:   1%|▏         | 84/6025 [00:31<36:59,  2.68batch/s]
Embedding:   1%|▏         | 85/6025 [00:31<37:00,  2.68batch/s]
Embedding:   1%|▏         | 86/6025 [00:31<36:57,  2.68batch/s]
Embedding:   1%|▏         | 87/6025 [00:32<36:54,  2.68batch/s]
Embedding:   1%|▏         | 88/6025 [00:32<36:55,  2.68batch/s]
Embedding:   1%|▏         | 89/6025 [00:33<37:00,  2.67batch/s]
Embedding:   1%|▏         | 90/6025 [00:33<37:03,  2.67batch/s]
Embedding:   2%|▏         | 91/6025 [00:33<36:55,  2.68batch/s]
Embedding:   2%|▏         | 92/6025 [00:34<36:54,  2.68batch/s]
Embedding:   2%|▏         | 93/6025 [00:34<36:56,  2.68batch/s]
Embedding:   2%|▏         | 94/6025 [00:34<36:58,  2.67batch/s]
Embedding:   2%|▏         | 95/6025 [00:35<37:01,  2.67batch/s]
Embedding:   2%|▏         | 96/6025 [00:35<37:03,  2.67batch/s]
Embedding:   2%|▏         | 97/6025 [00:36<36:58,  2.67batch/s]
Embedding:   2%|▏         | 98/6025 [00:36<37:02,  2.67batch/s]
Embedding:   2%|▏         | 99/6025 [00:36<37:02,  2.67batch/s]
Embedding:   2%|▏         | 100/6025 [00:37<37:01,  2.67batch/s]
Embedding:   2%|▏         | 101/6025 [00:37<37:00,  2.67batch/s]
Embedding:   2%|▏         | 102/6025 [00:37<37:08,  2.66batch/s]
Embedding:   2%|▏         | 103/6025 [00:38<37:06,  2.66batch/s]
Embedding:   2%|▏         | 104/6025 [00:38<37:10,  2.65batch/s]
Embedding:   2%|▏         | 105/6025 [00:39<37:21,  2.64batch/s]
Embedding:   2%|▏         | 106/6025 [00:39<37:24,  2.64batch/s]
Embedding:   2%|▏         | 107/6025 [00:39<37:29,  2.63batch/s]
Embedding:   2%|▏         | 108/6025 [00:40<37:45,  2.61batch/s]
Embedding:   2%|▏         | 109/6025 [00:40<37:42,  2.62batch/s]
Embedding:   2%|▏         | 110/6025 [00:41<37:49,  2.61batch/s]
Embedding:   2%|▏         | 111/6025 [00:41<37:52,  2.60batch/s]
Embedding:   2%|▏         | 112/6025 [00:41<37:55,  2.60batch/s]
Embedding:   2%|▏         | 113/6025 [00:42<37:54,  2.60batch/s]
Embedding:   2%|▏         | 114/6025 [00:42<37:43,  2.61batch/s]
Embedding:   2%|▏         | 115/6025 [00:42<37:47,  2.61batch/s]
Embedding:   2%|▏         | 116/6025 [00:43<37:46,  2.61batch/s]
Embedding:   2%|▏         | 117/6025 [00:43<37:38,  2.62batch/s]
Embedding:   2%|▏         | 118/6025 [00:44<37:44,  2.61batch/s]
Embedding:   2%|▏         | 119/6025 [00:44<37:28,  2.63batch/s]
Embedding:   2%|▏         | 120/6025 [00:44<37:26,  2.63batch/s]
Embedding:   2%|▏         | 121/6025 [00:45<37:30,  2.62batch/s]
Embedding:   2%|▏         | 122/6025 [00:45<37:28,  2.63batch/s]
Embedding:   2%|▏         | 123/6025 [00:45<37:34,  2.62batch/s]
Embedding:   2%|▏         | 124/6025 [00:46<37:39,  2.61batch/s]
Embedding:   2%|▏         | 125/6025 [00:46<37:43,  2.61batch/s]
Embedding:   2%|▏         | 126/6025 [00:47<37:37,  2.61batch/s]
Embedding:   2%|▏         | 127/6025 [00:47<37:36,  2.61batch/s]
Embedding:   2%|▏         | 128/6025 [00:47<37:35,  2.61batch/s]
Embedding:   2%|▏         | 129/6025 [00:48<37:37,  2.61batch/s]
Embedding:   2%|▏         | 130/6025 [00:48<37:38,  2.61batch/s]
Embedding:   2%|▏         | 131/6025 [00:49<37:37,  2.61batch/s]
Embedding:   2%|▏         | 132/6025 [00:49<37:45,  2.60batch/s]
Embedding:   2%|▏         | 133/6025 [00:49<37:49,  2.60batch/s]
Embedding:   2%|▏         | 134/6025 [00:50<37:48,  2.60batch/s]
Embedding:   2%|▏         | 135/6025 [00:50<37:48,  2.60batch/s]
Embedding:   2%|▏         | 136/6025 [00:50<37:49,  2.59batch/s]
Embedding:   2%|▏         | 137/6025 [00:51<37:51,  2.59batch/s]
Embedding:   2%|▏         | 138/6025 [00:51<37:53,  2.59batch/s]
Embedding:   2%|▏         | 139/6025 [00:52<37:54,  2.59batch/s]
Embedding:   2%|▏         | 140/6025 [00:52<38:05,  2.57batch/s]
Embedding:   2%|▏         | 141/6025 [00:52<38:17,  2.56batch/s]
Embedding:   2%|▏         | 142/6025 [00:53<38:32,  2.54batch/s]
Embedding:   2%|▏         | 143/6025 [00:53<38:38,  2.54batch/s]
Embedding:   2%|▏         | 144/6025 [00:54<38:33,  2.54batch/s]
Embedding:   2%|▏         | 145/6025 [00:54<38:33,  2.54batch/s]
Embedding:   2%|▏         | 146/6025 [00:54<38:35,  2.54batch/s]
Embedding:   2%|▏         | 147/6025 [00:55<38:27,  2.55batch/s]
Embedding:   2%|▏         | 148/6025 [00:55<38:21,  2.55batch/s]
Embedding:   2%|▏         | 149/6025 [00:56<38:14,  2.56batch/s]
Embedding:   2%|▏         | 150/6025 [00:56<38:22,  2.55batch/s]
Embedding:   3%|▎         | 151/6025 [00:56<38:13,  2.56batch/s]
Embedding:   3%|▎         | 152/6025 [00:57<38:13,  2.56batch/s]
Embedding:   3%|▎         | 153/6025 [00:57<38:14,  2.56batch/s]
Embedding:   3%|▎         | 154/6025 [00:58<38:03,  2.57batch/s]
Embedding:   3%|▎         | 155/6025 [00:58<38:09,  2.56batch/s]
Embedding:   3%|▎         | 156/6025 [00:58<38:17,  2.55batch/s]
Embedding:   3%|▎         | 157/6025 [00:59<38:20,  2.55batch/s]
Embedding:   3%|▎         | 158/6025 [00:59<38:25,  2.54batch/s]
Embedding:   3%|▎         | 159/6025 [00:59<38:22,  2.55batch/s]
Embedding:   3%|▎         | 160/6025 [01:00<38:20,  2.55batch/s]
Embedding:   3%|▎         | 161/6025 [01:00<38:23,  2.55batch/s]
Embedding:   3%|▎         | 162/6025 [01:01<38:20,  2.55batch/s]
Embedding:   3%|▎         | 163/6025 [01:01<38:30,  2.54batch/s]
Embedding:   3%|▎         | 164/6025 [01:01<38:24,  2.54batch/s]
Embedding:   3%|▎         | 165/6025 [01:02<38:30,  2.54batch/s]
Embedding:   3%|▎         | 166/6025 [01:02<38:32,  2.53batch/s]
Embedding:   3%|▎         | 167/6025 [01:03<38:25,  2.54batch/s]
Embedding:   3%|▎         | 168/6025 [01:03<38:25,  2.54batch/s]
Embedding:   3%|▎         | 169/6025 [01:03<38:31,  2.53batch/s]
Embedding:   3%|▎         | 170/6025 [01:04<38:33,  2.53batch/s]
Embedding:   3%|▎         | 171/6025 [01:04<38:37,  2.53batch/s]
Embedding:   3%|▎         | 172/6025 [01:05<39:08,  2.49batch/s]
Embedding:   3%|▎         | 173/6025 [01:05<39:11,  2.49batch/s]
Embedding:   3%|▎         | 174/6025 [01:05<39:01,  2.50batch/s]
Embedding:   3%|▎         | 175/6025 [01:06<39:04,  2.49batch/s]
Embedding:   3%|▎         | 176/6025 [01:06<39:15,  2.48batch/s]
Embedding:   3%|▎         | 177/6025 [01:07<39:30,  2.47batch/s]
Embedding:   3%|▎         | 178/6025 [01:07<39:06,  2.49batch/s]
Embedding:   3%|▎         | 179/6025 [01:07<39:08,  2.49batch/s]
Embedding:   3%|▎         | 180/6025 [01:08<39:02,  2.49batch/s]
Embedding:   3%|▎         | 181/6025 [01:08<38:55,  2.50batch/s]
Embedding:   3%|▎         | 182/6025 [01:09<39:08,  2.49batch/s]
Embedding:   3%|▎         | 183/6025 [01:09<39:10,  2.49batch/s]
Embedding:   3%|▎         | 184/6025 [01:09<39:16,  2.48batch/s]
Embedding:   3%|▎         | 185/6025 [01:10<39:03,  2.49batch/s]
Embedding:   3%|▎         | 186/6025 [01:10<39:02,  2.49batch/s]
Embedding:   3%|▎         | 187/6025 [01:11<39:07,  2.49batch/s]
Embedding:   3%|▎         | 188/6025 [01:11<39:12,  2.48batch/s]
Embedding:   3%|▎         | 189/6025 [01:11<39:20,  2.47batch/s]
Embedding:   3%|▎         | 190/6025 [01:12<39:35,  2.46batch/s]
Embedding:   3%|▎         | 191/6025 [01:12<39:34,  2.46batch/s]
Embedding:   3%|▎         | 192/6025 [01:13<39:38,  2.45batch/s]
Embedding:   3%|▎         | 193/6025 [01:13<39:25,  2.47batch/s]
Embedding:   3%|▎         | 194/6025 [01:14<39:23,  2.47batch/s]
Embedding:   3%|▎         | 195/6025 [01:14<39:13,  2.48batch/s]
Embedding:   3%|▎         | 196/6025 [01:14<39:21,  2.47batch/s]
Embedding:   3%|▎         | 197/6025 [01:15<39:28,  2.46batch/s]
Embedding:   3%|▎         | 198/6025 [01:15<39:34,  2.45batch/s]
Embedding:   3%|▎         | 199/6025 [01:16<39:50,  2.44batch/s]
Embedding:   3%|▎         | 200/6025 [01:16<40:00,  2.43batch/s]
Embedding:   3%|▎         | 201/6025 [01:16<40:00,  2.43batch/s]
Embedding:   3%|▎         | 202/6025 [01:17<40:00,  2.43batch/s]
Embedding:   3%|▎         | 203/6025 [01:17<40:26,  2.40batch/s]
Embedding:   3%|▎         | 204/6025 [01:18<40:30,  2.40batch/s]
Embedding:   3%|▎         | 205/6025 [01:18<40:28,  2.40batch/s]
Embedding:   3%|▎         | 206/6025 [01:18<40:44,  2.38batch/s]
Embedding:   3%|▎         | 207/6025 [01:19<40:34,  2.39batch/s]
Embedding:   3%|▎         | 208/6025 [01:19<40:35,  2.39batch/s]
Embedding:   3%|▎         | 209/6025 [01:20<40:28,  2.39batch/s]
Embedding:   3%|▎         | 210/6025 [01:20<40:26,  2.40batch/s]
Embedding:   4%|▎         | 211/6025 [01:21<40:32,  2.39batch/s]
Embedding:   4%|▎         | 212/6025 [01:21<40:32,  2.39batch/s]
Embedding:   4%|▎         | 213/6025 [01:21<40:37,  2.38batch/s]
Embedding:   4%|▎         | 214/6025 [01:22<40:37,  2.38batch/s]
Embedding:   4%|▎         | 215/6025 [01:22<40:45,  2.38batch/s]
Embedding:   4%|▎         | 216/6025 [01:23<40:41,  2.38batch/s]
Embedding:   4%|▎         | 217/6025 [01:23<40:31,  2.39batch/s]
Embedding:   4%|▎         | 218/6025 [01:24<40:39,  2.38batch/s]
Embedding:   4%|▎         | 219/6025 [01:24<40:47,  2.37batch/s]
Embedding:   4%|▎         | 220/6025 [01:24<40:54,  2.36batch/s]
Embedding:   4%|▎         | 221/6025 [01:25<40:37,  2.38batch/s]
Embedding:   4%|▎         | 222/6025 [01:25<40:44,  2.37batch/s]
Embedding:   4%|▎         | 223/6025 [01:26<40:43,  2.37batch/s]
Embedding:   4%|▎         | 224/6025 [01:26<40:53,  2.36batch/s]
Embedding:   4%|▎         | 225/6025 [01:26<40:49,  2.37batch/s]
Embedding:   4%|▍         | 226/6025 [01:27<40:46,  2.37batch/s]
Embedding:   4%|▍         | 227/6025 [01:27<40:39,  2.38batch/s]
Embedding:   4%|▍         | 228/6025 [01:28<40:48,  2.37batch/s]
Embedding:   4%|▍         | 229/6025 [01:28<41:03,  2.35batch/s]
Embedding:   4%|▍         | 230/6025 [01:29<41:02,  2.35batch/s]
Embedding:   4%|▍         | 231/6025 [01:29<41:04,  2.35batch/s]
Embedding:   4%|▍         | 232/6025 [01:29<41:12,  2.34batch/s]
Embedding:   4%|▍         | 233/6025 [01:30<41:10,  2.34batch/s]
Embedding:   4%|▍         | 234/6025 [01:30<41:12,  2.34batch/s]
Embedding:   4%|▍         | 235/6025 [01:31<41:21,  2.33batch/s]
Embedding:   4%|▍         | 236/6025 [01:31<41:14,  2.34batch/s]
Embedding:   4%|▍         | 237/6025 [01:32<41:03,  2.35batch/s]
Embedding:   4%|▍         | 238/6025 [01:32<41:08,  2.34batch/s]
Embedding:   4%|▍         | 239/6025 [01:32<40:51,  2.36batch/s]
Embedding:   4%|▍         | 240/6025 [01:33<40:43,  2.37batch/s]
Embedding:   4%|▍         | 241/6025 [01:33<40:42,  2.37batch/s]
Embedding:   4%|▍         | 242/6025 [01:34<40:35,  2.37batch/s]
Embedding:   4%|▍         | 243/6025 [01:34<40:38,  2.37batch/s]
Embedding:   4%|▍         | 244/6025 [01:35<40:24,  2.38batch/s]
Embedding:   4%|▍         | 245/6025 [01:35<40:16,  2.39batch/s]
Embedding:   4%|▍         | 246/6025 [01:35<40:08,  2.40batch/s]
Embedding:   4%|▍         | 247/6025 [01:36<39:56,  2.41batch/s]
Embedding:   4%|▍         | 248/6025 [01:36<40:00,  2.41batch/s]
Embedding:   4%|▍         | 249/6025 [01:37<40:03,  2.40batch/s]
Embedding:   4%|▍         | 250/6025 [01:37<40:05,  2.40batch/s]
Embedding:   4%|▍         | 251/6025 [01:37<40:10,  2.40batch/s]
Embedding:   4%|▍         | 252/6025 [01:38<40:15,  2.39batch/s]
Embedding:   4%|▍         | 253/6025 [01:38<39:48,  2.42batch/s]
Embedding:   4%|▍         | 254/6025 [01:39<39:33,  2.43batch/s]
Embedding:   4%|▍         | 255/6025 [01:39<39:33,  2.43batch/s]
Embedding:   4%|▍         | 256/6025 [01:39<39:37,  2.43batch/s]
Embedding:   4%|▍         | 257/6025 [01:40<39:29,  2.43batch/s]
Embedding:   4%|▍         | 258/6025 [01:40<39:23,  2.44batch/s]
Embedding:   4%|▍         | 259/6025 [01:41<39:23,  2.44batch/s]
Embedding:   4%|▍         | 260/6025 [01:41<39:13,  2.45batch/s]
Embedding:   4%|▍         | 261/6025 [01:42<39:19,  2.44batch/s]
Embedding:   4%|▍         | 262/6025 [01:42<39:17,  2.44batch/s]
Embedding:   4%|▍         | 263/6025 [01:42<39:18,  2.44batch/s]
Embedding:   4%|▍         | 264/6025 [01:43<39:11,  2.45batch/s]
Embedding:   4%|▍         | 265/6025 [01:43<39:37,  2.42batch/s]
Embedding:   4%|▍         | 266/6025 [01:44<39:39,  2.42batch/s]
Embedding:   4%|▍         | 267/6025 [01:44<39:31,  2.43batch/s]
Embedding:   4%|▍         | 268/6025 [01:44<39:19,  2.44batch/s]
Embedding:   4%|▍         | 269/6025 [01:45<39:08,  2.45batch/s]
Embedding:   4%|▍         | 270/6025 [01:45<39:05,  2.45batch/s]
Embedding:   4%|▍         | 271/6025 [01:46<39:07,  2.45batch/s]
Embedding:   5%|▍         | 272/6025 [01:46<38:51,  2.47batch/s]
Embedding:   5%|▍         | 273/6025 [01:46<38:47,  2.47batch/s]
Embedding:   5%|▍         | 274/6025 [01:47<39:00,  2.46batch/s]
Embedding:   5%|▍         | 275/6025 [01:47<38:46,  2.47batch/s]
Embedding:   5%|▍         | 276/6025 [01:48<38:53,  2.46batch/s]
Embedding:   5%|▍         | 277/6025 [01:48<38:54,  2.46batch/s]
Embedding:   5%|▍         | 278/6025 [01:48<38:36,  2.48batch/s]
Embedding:   5%|▍         | 279/6025 [01:49<38:29,  2.49batch/s]
Embedding:   5%|▍         | 280/6025 [01:49<38:35,  2.48batch/s]
Embedding:   5%|▍         | 281/6025 [01:50<38:35,  2.48batch/s]
Embedding:   5%|▍         | 282/6025 [01:50<38:35,  2.48batch/s]
Embedding:   5%|▍         | 283/6025 [01:50<38:32,  2.48batch/s]
Embedding:   5%|▍         | 284/6025 [01:51<38:17,  2.50batch/s]
Embedding:   5%|▍         | 285/6025 [01:51<38:16,  2.50batch/s]
Embedding:   5%|▍         | 286/6025 [01:52<38:20,  2.49batch/s]
Embedding:   5%|▍         | 287/6025 [01:52<38:23,  2.49batch/s]
Embedding:   5%|▍         | 288/6025 [01:52<38:11,  2.50batch/s]
Embedding:   5%|▍         | 289/6025 [01:53<38:12,  2.50batch/s]
Embedding:   5%|▍         | 290/6025 [01:53<38:00,  2.51batch/s]
Embedding:   5%|▍         | 291/6025 [01:54<37:51,  2.52batch/s]
Embedding:   5%|▍         | 292/6025 [01:54<38:20,  2.49batch/s]
Embedding:   5%|▍         | 293/6025 [01:54<38:18,  2.49batch/s]
Embedding:   5%|▍         | 294/6025 [01:55<38:14,  2.50batch/s]
Embedding:   5%|▍         | 295/6025 [01:55<38:19,  2.49batch/s]
Embedding:   5%|▍         | 296/6025 [01:56<38:35,  2.47batch/s]
Embedding:   5%|▍         | 297/6025 [01:56<38:21,  2.49batch/s]
Embedding:   5%|▍         | 298/6025 [01:56<38:15,  2.50batch/s]
Embedding:   5%|▍         | 299/6025 [01:57<38:03,  2.51batch/s]
Embedding:   5%|▍         | 300/6025 [01:57<38:03,  2.51batch/s]
Embedding:   5%|▍         | 301/6025 [01:58<37:45,  2.53batch/s]

## 7. Bảng thống kê embedding

In [12]:
def load_json(path):
    return json.loads(Path(path).read_text(encoding="utf-8"))

rows = []
for strategy in STRATEGIES:
    strategy_dir = DENSE_OUTPUT_ROOT / strategy
    stats_path = strategy_dir / "embedding_stats.json"
    manifest_path = strategy_dir / "manifest.json"
    if not stats_path.exists():
        print(f"Missing stats for {strategy}: {stats_path}")
        continue
    stats = load_json(stats_path)
    manifest = load_json(manifest_path)
    rows.append({
        "strategy": strategy,
        "chunks": stats["chunks_embedded"],
        "dimension": stats["embedding_dimension"],
        "batch_size": stats["batch_size"],
        "elapsed_seconds": stats["elapsed_seconds"],
        "chunks_per_second": stats["chunks_per_second"],
        "avg_tokens": stats["token_stats"]["avg"],
        "max_tokens": stats["token_stats"]["max"],
        "avg_chars": stats["char_stats"]["avg"],
        "max_chars": stats["char_stats"]["max"],
        "embeddings_path": manifest["embeddings_path"],
        "stats_path": str(stats_path),
    })

embed_stats_df = pd.DataFrame(rows).sort_values("strategy")
display(embed_stats_df)

summary_csv = PROJECT_ROOT / "src" / "embed" / "output" / "embedding_stats_summary.csv"
embed_stats_df.to_csv(summary_csv, index=False, encoding="utf-8-sig")
print("Saved:", summary_csv)

,strategy,chunks,dimension,batch_size,elapsed_seconds,chunks_per_second,avg_tokens,max_tokens,avg_chars,max_chars,embeddings_path,stats_path
3,langchain_recursive,98156,1024,4,4261.312797,23.0342,139.0185,303,639.4621,1381,/content/Text-Mining---RAG-on-News/src/embed/o...,/content/Text-Mining---RAG-on-News/src/embed/o...
1,llamaindex,48977,1024,4,2916.000963,16.7959,219.1943,362,1010.7891,1666,/content/Text-Mining---RAG-on-News/src/embed/o...,/content/Text-Mining---RAG-on-News/src/embed/o...
2,structured,25464,1024,4,2577.720623,9.8785,396.7930,587,1819.2870,3213,/content/Text-Mining---RAG-on-News/src/embed/o...,/content/Text-Mining---RAG-on-News/src/embed/o...
0,token,24099,1024,4,2429.915227,9.9176,397.9590,533,1831.9081,3099,/content/Text-Mining---RAG-on-News/src/embed/o...,/content/Text-Mining---RAG-on-News/src/embed/o...

Saved: /content/Text-Mining---RAG-on-News/src/embed/output/embedding_stats_summary.csv

## 8. Debug chunk dài nhất và mẫu đã embed

In [13]:
for strategy in STRATEGIES:
    strategy_dir = DENSE_OUTPUT_ROOT / strategy
    stats_path = strategy_dir / "embedding_stats.json"
    samples_path = strategy_dir / "debug_samples.jsonl"
    if not stats_path.exists():
        continue
    stats = load_json(stats_path)
    display(Markdown(f"### {strategy}: longest chunks"))
    display(pd.DataFrame(stats["longest_chunks"]))
    if samples_path.exists():
        samples = [json.loads(line) for line in samples_path.read_text(encoding="utf-8").splitlines() if line.strip()]
        display(Markdown(f"### {strategy}: debug samples"))
        display(pd.DataFrame(samples))

### token: longest chunks

,chunk_id,article_id,strategy,estimated_tokens,text_chars,title,category
0,75615_token_0000,75615,token,533,2441,"Tới Breda, Hà Lan thăm lâu đài trên mặt nước v...",Du lịch
1,77248_token_0000,77248,token,532,2460,"Du lịch Phú Quốc, bạn đã biết các địa điểm này...",Du lịch
2,77124_token_0000,77124,token,531,2416,Những địa điểm hấp dẫn khi đến Lyon du khách t...,Du lịch
3,77535_token_0000,77535,token,531,2375,5 món đặc sản ở Vĩnh Hy không thể bỏ lỡ trong ...,Du lịch
4,76610_token_0000,76610,token,530,2356,Lý Sơn không chỉ có tỏi ngon mà còn 'quá trời'...,Du lịch
5,77750_token_0000,77750,token,520,2450,'Điểm danh' những kinh đô thời trang hàng đầu ...,Du lịch
6,75902_token_0000,75902,token,519,2389,Tham khảo 5 điểm dừng nghỉ được yêu thích tại ...,Du lịch
7,76062_token_0000,76062,token,518,2383,Kinh nghiệm cắm trại hồ Trị An 'cực chill' cho...,Du lịch
8,77657_token_0000,77657,token,518,2336,Khám phá Buôn Ma Thuột: Thủ phủ cà phê đậm văn...,Du lịch
9,110946_token_0000,110946,token,517,2309,Người tiêu dùng Việt Nam dẫn đầu khu vực về mứ...,Kinh doanh

### token: debug samples

,chunk_id,article_id,strategy,implementation,chunk_index,title,category,estimated_tokens,text_chars,embedding_input_preview,chunk_text_preview
0,211640_token_0000,211640,token,internal_token_window,0,"Không muốn hại thận, cần hạn chế 4 loại thịt",Sức khỏe,452,2122,"passage: Tiêu đề: Không muốn hại thận, cần hạn...","Theo Sohu, nhiều người khi nhắc đến tăng axit ..."
1,211640_token_0001,211640,token,internal_token_window,1,"Không muốn hại thận, cần hạn chế 4 loại thịt",Sức khỏe,319,1490,"passage: Tiêu đề: Không muốn hại thận, cần hạn...","đặc biệt khi kết hợp với lẩu hay canh hầm, có ..."
2,152685_token_0000,152685,token,internal_token_window,0,Bất ngờ danh tính doanh nghiệp trúng thầu khu ...,Bất động sản,471,2141,passage: Tiêu đề: Bất ngờ danh tính doanh nghi...,"Ngày 11/1, thông tin từ Sở TN-MT tỉnh Thừa Thi..."
3,152685_token_0001,152685,token,internal_token_window,1,Bất ngờ danh tính doanh nghiệp trúng thầu khu ...,Bất động sản,173,809,passage: Tiêu đề: Bất ngờ danh tính doanh nghi...,"khu đất nói trên được công bố, nhiều người tỏ ..."
4,132354_token_0000,132354,token,internal_token_window,0,Bí thư Tỉnh ủy Khánh Hòa: 'An toàn của người d...,Thời sự,467,2110,passage: Tiêu đề: Bí thư Tỉnh ủy Khánh Hòa: 'A...,"Chiều và tối 6.11, ông Nghiêm Xuân Thành, Bí t..."

### llamaindex: longest chunks

,chunk_id,article_id,strategy,estimated_tokens,text_chars,title,category
0,77750_llamaindex_0002,77750,llamaindex,362,1666,'Điểm danh' những kinh đô thời trang hàng đầu ...,Du lịch
1,110770_llamaindex_0002,110770,llamaindex,352,1654,"NHNN đề nghị Bộ Công an, Tài chính hỗ trợ đấu ...",Kinh doanh
2,112616_llamaindex_0004,112616,llamaindex,348,1652,"Techcombank, thương hiệu ngân hàng tư nhân giá...",Kinh doanh
3,76953_llamaindex_0003,76953,llamaindex,338,1577,"Làng văn hóa đầy màu sắc Gamcheon, Hàn Quốc",Du lịch
4,250532_llamaindex_0001,250532,llamaindex,330,1468,"Xe tải nặng vô tư lùi không quan sát, suýt cán...",Xe
5,141293_llamaindex_0001,141293,llamaindex,330,1541,Không được đưa lao động đi làm việc tại Israel...,Thời sự
6,33761_llamaindex_0001,33761,llamaindex,329,1557,Lan truyền video sai sự thật về khoang hành kh...,Thế giới
7,252024_llamaindex_0000,252024,llamaindex,329,1503,Audi Việt Nam triệu hồi xe điện e-tron GT và R...,Xe
8,117298_llamaindex_0004,117298,llamaindex,328,1467,Cấy chỉ làm đẹp và giảm béo: Liệu pháp làm đẹp...,Sức khỏe
9,185741_llamaindex_0001,185741,llamaindex,328,1547,Người dùng không cần phải khoá thẻ hay đổi mật...,Khoa học công nghệ

### llamaindex: debug samples

,chunk_id,article_id,strategy,implementation,chunk_index,title,category,estimated_tokens,text_chars,embedding_input_preview,chunk_text_preview
0,211640_llamaindex_0000,211640,llamaindex,llama_index.core.node_parser.SentenceSplitter,0,"Không muốn hại thận, cần hạn chế 4 loại thịt",Sức khỏe,219,1027,"passage: Tiêu đề: Không muốn hại thận, cần hạn...","Theo Sohu, nhiều người khi nhắc đến tăng axit ..."
1,211640_llamaindex_0001,211640,llamaindex,llama_index.core.node_parser.SentenceSplitter,1,"Không muốn hại thận, cần hạn chế 4 loại thịt",Sức khỏe,197,928,"passage: Tiêu đề: Không muốn hại thận, cần hạn...","Ngoài thịt dê, nhiều loại thịt đỏ khác như thị..."
2,211640_llamaindex_0002,211640,llamaindex,llama_index.core.node_parser.SentenceSplitter,2,"Không muốn hại thận, cần hạn chế 4 loại thịt",Sức khỏe,208,980,"passage: Tiêu đề: Không muốn hại thận, cần hạn...","Bên cạnh đó, một số thực phẩm khác cũng chứa n..."
3,211640_llamaindex_0003,211640,llamaindex,llama_index.core.node_parser.SentenceSplitter,3,"Không muốn hại thận, cần hạn chế 4 loại thịt",Sức khỏe,174,813,"passage: Tiêu đề: Không muốn hại thận, cần hạn...",Nhiều người chuyển từ thịt đỏ sang ăn hải sản ...
4,211640_llamaindex_0004,211640,llamaindex,llama_index.core.node_parser.SentenceSplitter,4,"Không muốn hại thận, cần hạn chế 4 loại thịt",Sức khỏe,142,658,"passage: Tiêu đề: Không muốn hại thận, cần hạn...","Việc duy trì cân nặng hợp lý, uống đủ nước, ăn..."

### structured: longest chunks

,chunk_id,article_id,strategy,estimated_tokens,text_chars,title,category
0,241001_structured_0001,241001,structured,587,2676,Những trường hợp nào thì đóng cửa trung tâm đă...,Thời sự
1,183147_structured_0003,183147,structured,554,2636,"Thái Nguyên đẩy mạnh chuyển đổi số, tạo bứt ph...",Khoa học công nghệ
2,131721_structured_0002,131721,structured,538,2533,Trao trực tiếp 150 triệu đồng tại giải pickleb...,Thể thao
3,77248_structured_0000,77248,structured,524,2423,"Du lịch Phú Quốc, bạn đã biết các địa điểm này...",Du lịch
4,75902_structured_0000,75902,structured,515,2371,Tham khảo 5 điểm dừng nghỉ được yêu thích tại ...,Du lịch
5,76062_structured_0001,76062,structured,514,2347,Kinh nghiệm cắm trại hồ Trị An 'cực chill' cho...,Du lịch
6,76610_structured_0000,76610,structured,513,2274,Lý Sơn không chỉ có tỏi ngon mà còn 'quá trời'...,Du lịch
7,77750_structured_0000,77750,structured,513,2410,'Điểm danh' những kinh đô thời trang hàng đầu ...,Du lịch
8,77124_structured_0000,77124,structured,512,2329,Những địa điểm hấp dẫn khi đến Lyon du khách t...,Du lịch
9,77179_structured_0000,77179,structured,512,2371,Chiêm ngưỡng 5 quán cà phê ở Bangkok đẹp ngất ...,Du lịch

### structured: debug samples

,chunk_id,article_id,strategy,implementation,chunk_index,title,category,estimated_tokens,text_chars,embedding_input_preview,chunk_text_preview
0,211640_structured_0000,211640,structured,internal_structured_sentence_window,0,"Không muốn hại thận, cần hạn chế 4 loại thịt",Sức khỏe,441,2072,"passage: Tiêu đề: Không muốn hại thận, cần hạn...","Theo Sohu, nhiều người khi nhắc đến tăng axit ..."
1,211640_structured_0001,211640,structured,internal_structured_sentence_window,1,"Không muốn hại thận, cần hạn chế 4 loại thịt",Sức khỏe,347,1620,"passage: Tiêu đề: Không muốn hại thận, cần hạn...","Nội tạng động vật như gan, thận, lòng, dạ dày ..."
2,152685_structured_0000,152685,structured,internal_structured_sentence_window,0,Bất ngờ danh tính doanh nghiệp trúng thầu khu ...,Bất động sản,465,2111,passage: Tiêu đề: Bất ngờ danh tính doanh nghi...,"Ngày 11/1, thông tin từ Sở TN-MT tỉnh Thừa Thi..."
3,152685_structured_0001,152685,structured,internal_structured_sentence_window,1,Bất ngờ danh tính doanh nghiệp trúng thầu khu ...,Bất động sản,181,843,passage: Tiêu đề: Bất ngờ danh tính doanh nghi...,Sau khi kết quả trúng đấu giá của khu đất nói ...
4,132354_structured_0000,132354,structured,internal_structured_sentence_window,0,Bí thư Tỉnh ủy Khánh Hòa: 'An toàn của người d...,Thời sự,447,2009,passage: Tiêu đề: Bí thư Tỉnh ủy Khánh Hòa: 'A...,"Chiều và tối 6. 11, ông Nghiêm Xuân Thành, Bí ..."

### langchain_recursive: longest chunks

,chunk_id,article_id,strategy,estimated_tokens,text_chars,title,category
0,108978_langchain_recursive_0000,108978,langchain_recursive,303,1381,"Chuyển đổi số trong thu thập, giám sát thông s...",Kinh doanh
1,101967_langchain_recursive_0000,101967,langchain_recursive,289,1272,Điểm thi lớp 10 của TP.HCM: Môn toán có 36 thí...,Giáo dục
2,152719_langchain_recursive_0000,152719,langchain_recursive,287,1257,Về Nam Ô nghe giấc mơ làng biển,Bất động sản
3,45089_langchain_recursive_0000,45089,langchain_recursive,287,1255,Có tiền sao không xài?,Thời sự
4,208438_langchain_recursive_0000,208438,langchain_recursive,284,1267,Docquity Việt Nam tài trợ hội nghị Sản Phụ kho...,Sức khỏe
5,239260_langchain_recursive_0000,239260,langchain_recursive,283,1279,"Va chạm trên cao tốc: Một ô tô lật ngang, một ...",Thời sự
6,121007_langchain_recursive_0000,121007,langchain_recursive,283,1308,Hai tàu ngầm Nga bắn trúng mục tiêu mồi ở vùng...,Thế giới
7,203640_langchain_recursive_0000,203640,langchain_recursive,281,1245,Bắt Chi cục trưởng Thi hành án dân sự ở Bến Tr...,Pháp luật
8,246677_langchain_recursive_0000,246677,langchain_recursive,280,1278,Phá đường dây ma túy từ nước ngoài về Việt Nam...,Thời sự
9,216863_langchain_recursive_0000,216863,langchain_recursive,278,1294,Ukraine bắn hạ máy bay không người lái mới siê...,Thế giới

### langchain_recursive: debug samples

,chunk_id,article_id,strategy,implementation,chunk_index,title,category,estimated_tokens,text_chars,embedding_input_preview,chunk_text_preview
0,211640_langchain_recursive_0000,211640,langchain_recursive,langchain_text_splitters.RecursiveCharacterTex...,0,"Không muốn hại thận, cần hạn chế 4 loại thịt",Sức khỏe,135,630,"passage: Tiêu đề: Không muốn hại thận, cần hạn...","Theo Sohu, nhiều người khi nhắc đến tăng axit ..."
1,211640_langchain_recursive_0001,211640,langchain_recursive,langchain_text_splitters.RecursiveCharacterTex...,1,"Không muốn hại thận, cần hạn chế 4 loại thịt",Sức khỏe,131,616,"passage: Tiêu đề: Không muốn hại thận, cần hạn...",. Thịt dê được xếp vào nhóm thịt đỏ nên purin ...
2,211640_langchain_recursive_0002,211640,langchain_recursive,langchain_text_splitters.RecursiveCharacterTex...,2,"Không muốn hại thận, cần hạn chế 4 loại thịt",Sức khỏe,128,605,"passage: Tiêu đề: Không muốn hại thận, cần hạn...",". Ngoài thịt dê, nhiều loại thịt đỏ khác như t..."
3,211640_langchain_recursive_0003,211640,langchain_recursive,langchain_text_splitters.RecursiveCharacterTex...,3,"Không muốn hại thận, cần hạn chế 4 loại thịt",Sức khỏe,123,575,"passage: Tiêu đề: Không muốn hại thận, cần hạn...",. Trong nhóm người có axit uric cao kèm giảm c...
4,211640_langchain_recursive_0004,211640,langchain_recursive,langchain_text_splitters.RecursiveCharacterTex...,4,"Không muốn hại thận, cần hạn chế 4 loại thịt",Sức khỏe,126,604,"passage: Tiêu đề: Không muốn hại thận, cần hạn...",". Nội tạng động vật như gan, thận, lòng, dạ dà..."

## 9. Search thử trên một strategy đã embed

In [14]:
QUERY = "Tin tức về công nghệ AI tại Việt Nam"
SEARCH_STRATEGY = STRATEGIES[0]

search_cmd = [
    sys.executable, "-m", "src.embed.dense_search",
    "--index-dir", DENSE_OUTPUT_ROOT / SEARCH_STRATEGY,
    "--query", QUERY,
    "--top-k", 5,
    "--model", MODEL_NAME,
]
run_cli(search_cmd)

$ /usr/bin/python3 -m src.embed.dense_search --index-dir /content/Text-Mining---RAG-on-News/src/embed/output/dense/token --query Tin tức về công nghệ AI tại Việt Nam --top-k 5 --model intfloat/multilingual-e5-large


Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]
Loading weights: 100%|██████████| 391/391 [00:00<00:00, 6106.77it/s]
{
  "query": "Tin tức về công nghệ AI tại Việt Nam",
  "results": [
    {
      "chunk_id": "65416_token_0002",
      "article_id": "65416",
      "score": 0.8897868990898132,
      "title": "AI Việt góp phần định hình bối cảnh trí tuệ nhân tạo Đông Nam Á",
      "category": "Khoa học công nghệ",
      "strategy": "token",
      "chunk_index": 2,
      "text": "Tiêu đề: AI Việt góp phần định hình bối cảnh trí tuệ nhân tạo Đông Nam Á\nMô tả: Với rào cản kỹ thuật được hạ thấp, các startup trí tuệ nhân tạo ở Đông Nam Á, trong đó có công ty AI Việt Nam có thể tập trung vào thế mạnh của mình là giải quyết vấn đề kinh doanh thực tế .\nChuyên mục: Khoa học công nghệ\nĐoạn nội dung:\ncác doanh nghiệp mạnh hơn đến từ Mỹ, Trung Quốc... chưa có được. AI Hay hiện được cung cấp thông qua website và ứng dụng cùng tên trên các kho phần mềm của hai nền tảng di động iOS lẫn Android. Xuất hiện lần đầu vào tháng 6.2024, chỉ sau một năm hoạt động, AI Hay hiện có hơn 10 triệu lượt tải ứng dụng, xử lý thành công hơn 100 triệu câu hỏi mỗi tháng, đồng thời nhận được đánh giá 4,8/5 điểm từ hơn 140.000 người dùng thực tế.",
      "chunk_text": "các doanh nghiệp mạnh hơn đến từ Mỹ, Trung Quốc... chưa có được. AI Hay hiện được cung cấp thông qua website và ứng dụng cùng tên trên các kho phần mềm của hai nền tảng di động iOS lẫn Android. Xuất hiện lần đầu vào tháng 6.2024, chỉ sau một năm hoạt động, AI Hay hiện có hơn 10 triệu lượt tải ứng dụng, xử lý thành công hơn 100 triệu câu hỏi mỗi tháng, đồng thời nhận được đánh giá 4,8/5 điểm từ hơn 140.000 người dùng thực tế."
    },
    {
      "chunk_id": "65416_token_0000",
      "article_id": "65416",
      "score": 0.8880772590637207,
      "title": "AI Việt góp phần định hình bối cảnh trí tuệ nhân tạo Đông Nam Á",
      "category": "Khoa học công nghệ",
      "strategy": "token",
      "chunk_index": 0,
      "text": "Tiêu đề: AI Việt góp phần định hình bối cảnh trí tuệ nhân tạo Đông Nam Á\nMô tả: Với rào cản kỹ thuật được hạ thấp, các startup trí tuệ nhân tạo ở Đông Nam Á, trong đó có công ty AI Việt Nam có thể tập trung vào thế mạnh của mình là giải quyết vấn đề kinh doanh thực tế .\nChuyên mục: Khoa học công nghệ\nĐoạn nội dung:\nCác khoản đầu tư mạo hiểm (VC) toàn cầu tiếp tục xoay quanh trí tuệ nhân tạo, với 49% trong tổng số 205,6 tỉ USD huy động được trong nửa đầu năm 2025 chảy vào các công ty AI, theo dữ liệu của Crunchbase. Phần lớn (gần 90 tỉ USD) trong tổng số 100,8 tỉ USD dành cho trí tuệ nhân tạo được đổ vào các công ty Mỹ. Dù điều đó khiến Đông Nam Á có vẻ mờ nhạt trên bản đồ AI toàn cầu, một số công ty trong khu vực, trong đó có doanh nghiệp AI Việt Nam, vẫn huy động được các khoản vốn đáng kể. Việt Nam có số lượng startup AI nhiều đáng kể tại Đông Nam Á Ảnh chụp màn hình TechInAsia Một vài trong số các công ty này tập trung vào AI có khả năng tự hành (Agentic AI), phát triển các giải pháp cho phép AI tự động hoàn thành nhiệm vụ thay cho người dùng. Giữa \"một rừng\" tên tuổi chủ yếu đến từ Singapore và Indonesia, trong danh sách 50 startup sáng giá của TechAsia có 2 doanh nghiệp Việt làm AI, nhưng hướng đi khác nhau. Trong đó, AI Hay tập trung phát triển nền tảng cộng đồng nhằm thỏa mãn nhu cầu hỏi đáp, tìm kiếm thông tin của hàng triệu người Việt. Doanh nghiệp còn lại thì tập trung cho giải pháp giúp nông dân nuôi tôm. Tháng 7 vừa qua, AI Hay - nền tảng kết hợp trí tuệ nhân tạo tạo sinh với mạng xã hội do các kỹ sư Việt Nam phát triển đã công bố gọi vốn thành công vòng series A với số tiền 10 triệu USD, nâng tổng vốn huy động của đơn vị lên 18 triệu USD, tiến gần hơn đến mục tiêu mang đến công cụ AI thông minh, dễ tiếp cận và phục vụ cuộc sống hàng ngày của người Việt. Theo báo cáo thị trường AI tiêu dùng Việt Nam năm 2025 của Decision Lab, AI Hay đứng thứ 6 trong danh sách 10 công cụ trí tuệ nhân tạo được sử dụng nhiều nhất Việt Nam trong quý 2/2025. Báo cáo nhận định dù các sản phẩm quốc tế đang chiếm ưu thế và mạnh mẽ, nền tảng AI \"nội địa\" vẫn ghi được dấu ấn nhờ sự gần gũi và thấu hiểu người",
      "chunk_text": "Các khoản đầu tư mạo hiểm (VC) toàn cầu tiếp tục xoay quanh trí tuệ nhân tạo, với 49% trong tổng số 205,6 tỉ USD huy động được trong nửa đầu năm 2025 chảy vào các công ty AI, theo dữ liệu của Crunchbase. Phần lớn (gần 90 tỉ USD) trong tổng số 100,8 tỉ USD dành cho trí tuệ nhân tạo được đổ vào các công ty Mỹ. Dù điều đó khiến Đông Nam Á có vẻ mờ nhạt trên bản đồ AI toàn cầu, một số công ty trong khu vực, trong đó có doanh nghiệp AI Việt Nam, vẫn huy động được các khoản vốn đáng kể. Việt Nam có số lượng startup AI nhiều đáng kể tại Đông Nam Á Ảnh chụp màn hình TechInAsia Một vài trong số các công ty này tập trung vào AI có khả năng tự hành (Agentic AI), phát triển các giải pháp cho phép AI tự động hoàn thành nhiệm vụ thay cho người dùng. Giữa \"một rừng\" tên tuổi chủ yếu đến từ Singapore và Indonesia, trong danh sách 50 startup sáng giá của TechAsia có 2 doanh nghiệp Việt làm AI, nhưng hướng đi khác nhau. Trong đó, AI Hay tập trung phát triển nền tảng cộng đồng nhằm thỏa mãn nhu cầu hỏi đáp, tìm kiếm thông tin của hàng triệu người Việt. Doanh nghiệp còn lại thì tập trung cho giải pháp giúp nông dân nuôi tôm. Tháng 7 vừa qua, AI Hay - nền tảng kết hợp trí tuệ nhân tạo tạo sinh với mạng xã hội do các kỹ sư Việt Nam phát triển đã công bố gọi vốn thành công vòng series A với số tiền 10 triệu USD, nâng tổng vốn huy động của đơn vị lên 18 triệu USD, tiến gần hơn đến mục tiêu mang đến công cụ AI thông minh, dễ tiếp cận và phục vụ cuộc sống hàng ngày của người Việt. Theo báo cáo thị trường AI tiêu dùng Việt Nam năm 2025 của Decision Lab, AI Hay đứng thứ 6 trong danh sách 10 công cụ trí tuệ nhân tạo được sử dụng nhiều nhất Việt Nam trong quý 2/2025. Báo cáo nhận định dù các sản phẩm quốc tế đang chiếm ưu thế và mạnh mẽ, nền tảng AI \"nội địa\" vẫn ghi được dấu ấn nhờ sự gần gũi và thấu hiểu người"
    },
    {
      "chunk_id": "65416_token_0001",
      "article_id": "65416",
      "score": 0.8763104677200317,
      "title": "AI Việt góp phần định hình bối cảnh trí tuệ nhân tạo Đông Nam Á",
      "category": "Khoa học công nghệ",
      "strategy": "token",
      "chunk_index": 1,
      "text": "Tiêu đề: AI Việt góp phần định hình bối cảnh trí tuệ nhân tạo Đông Nam Á\nMô tả: Với rào cản kỹ thuật được hạ thấp, các startup trí tuệ nhân tạo ở Đông Nam Á, trong đó có công ty AI Việt Nam có thể tập trung vào thế mạnh của mình là giải quyết vấn đề kinh doanh thực tế .\nChuyên mục: Khoa học công nghệ\nĐoạn nội dung:\nhàng ngày của người Việt. Theo báo cáo thị trường AI tiêu dùng Việt Nam năm 2025 của Decision Lab, AI Hay đứng thứ 6 trong danh sách 10 công cụ trí tuệ nhân tạo được sử dụng nhiều nhất Việt Nam trong quý 2/2025. Báo cáo nhận định dù các sản phẩm quốc tế đang chiếm ưu thế và mạnh mẽ, nền tảng AI \"nội địa\" vẫn ghi được dấu ấn nhờ sự gần gũi và thấu hiểu người Việt. Nhận định này cũng được thể hiện qua việc nền tảng của Việt Nam đứng thứ 2 danh sách về mức độ hài lòng của người dùng (47%), chỉ đứng sau ChatGTP của OpenAI (51%). Công ty AI Việt nhận được mức độ hài lòng cao thứ 2 ngay tại thị trường quê hương Ảnh chụp màn hình \"Chúng tôi tin rằng AI không chỉ dành cho chuyên gia, mà phải trở thành công cụ phổ thông, đến được với từng người Việt, bắt đầu từ sinh viên - những người sẽ kiến tạo tương lai đất nước\", anh Trần Quang Đức, CEO AI Hay từng chia sẻ sau khi gọi vốn thành công gần đây. Ưu điểm của nền tảng này là giúp người dùng đặt bất kỳ câu hỏi nào và nhận lại kết quả chính xác, tin cậy, có trích dẫn minh bạch, đặc biệt phù hợp với văn hóa, ngôn ngữ Việt Nam. Bên cạnh việc hỗ trợ tiếp cận tri thức, công cụ còn xây dựng cộng đồng tương tác, nơi người dùng chia sẻ kiến thức, cùng thảo luận và đóng góp ý kiến, tạo ra môi trường học hỏi văn minh. Hướng đi này cũng tương đồng với nhiều startup AI khác tại Đông Nam Á, nơi công ty khởi nghiệp nhìn thấy cơ hội phát triển nhờ khả năng am hiểu văn hóa bản địa cũng như khu vực, điều mà các doanh nghiệp mạnh hơn đến từ Mỹ, Trung Quốc... chưa có được. AI Hay hiện được cung cấp thông qua website và ứng dụng cùng tên trên các kho phần mềm của hai nền tảng di động iOS lẫn Android. Xuất hiện lần đầu vào tháng 6.2024, chỉ sau một năm hoạt động, AI Hay hiện có hơn 10 triệu lượt tải ứng dụng, xử lý thành công hơn 100 triệu câu hỏi mỗi tháng, đồng thời nhận được",
      "chunk_text": "hàng ngày của người Việt. Theo báo cáo thị trường AI tiêu dùng Việt Nam năm 2025 của Decision Lab, AI Hay đứng thứ 6 trong danh sách 10 công cụ trí tuệ nhân tạo được sử dụng nhiều nhất Việt Nam trong quý 2/2025. Báo cáo nhận định dù các sản phẩm quốc tế đang chiếm ưu thế và mạnh mẽ, nền tảng AI \"nội địa\" vẫn ghi được dấu ấn nhờ sự gần gũi và thấu hiểu người Việt. Nhận định này cũng được thể hiện qua việc nền tảng của Việt Nam đứng thứ 2 danh sách về mức độ hài lòng của người dùng (47%), chỉ đứng sau ChatGTP của OpenAI (51%). Công ty AI Việt nhận được mức độ hài lòng cao thứ 2 ngay tại thị trường quê hương Ảnh chụp màn hình \"Chúng tôi tin rằng AI không chỉ dành cho chuyên gia, mà phải trở thành công cụ phổ thông, đến được với từng người Việt, bắt đầu từ sinh viên - những người sẽ kiến tạo tương lai đất nước\", anh Trần Quang Đức, CEO AI Hay từng chia sẻ sau khi gọi vốn thành công gần đây. Ưu điểm của nền tảng này là giúp người dùng đặt bất kỳ câu hỏi nào và nhận lại kết quả chính xác, tin cậy, có trích dẫn minh bạch, đặc biệt phù hợp với văn hóa, ngôn ngữ Việt Nam. Bên cạnh việc hỗ trợ tiếp cận tri thức, công cụ còn xây dựng cộng đồng tương tác, nơi người dùng chia sẻ kiến thức, cùng thảo luận và đóng góp ý kiến, tạo ra môi trường học hỏi văn minh. Hướng đi này cũng tương đồng với nhiều startup AI khác tại Đông Nam Á, nơi công ty khởi nghiệp nhìn thấy cơ hội phát triển nhờ khả năng am hiểu văn hóa bản địa cũng như khu vực, điều mà các doanh nghiệp mạnh hơn đến từ Mỹ, Trung Quốc... chưa có được. AI Hay hiện được cung cấp thông qua website và ứng dụng cùng tên trên các kho phần mềm của hai nền tảng di động iOS lẫn Android. Xuất hiện lần đầu vào tháng 6.2024, chỉ sau một năm hoạt động, AI Hay hiện có hơn 10 triệu lượt tải ứng dụng, xử lý thành công hơn 100 triệu câu hỏi mỗi tháng, đồng thời nhận được"
    },
    {
      "chunk_id": "44869_token_0002",
      "article_id": "44869",
      "score": 0.8724695444107056,
      "title": "ChatGPT ra đời, vận hội cho Việt Nam từ AI",
      "category": "Thời sự",
      "strategy": "token",
      "chunk_index": 2,
      "text": "Tiêu đề: ChatGPT ra đời, vận hội cho Việt Nam từ AI\nMô tả: ChatGPT ra đời đã hiện thực hóa khái niệm trợ lý trí tuệ nhân tạo (trợ lý AI).\nChuyên mục: Thời sự\nĐoạn nội dung:\nnhanh hơn, đặc biệt là cơ hội cho vùng sâu vùng xa, thu hẹp khoảng cách với các trung tâm lớn, để mỗi công dân Việt Nam trở thành một nhà sáng tạo. Chủ trương kinh tế số - xã hội số trong công cuộc chuyển đổi số của Việt Nam cần được tiếp tục nhanh hơn và thực chất hơn chứ không chỉ là những con số thành tích. Với sự vận dụng AI, kinh tế số - xã hội số nếu được triển khai triệt để, nhanh chóng và đặc biệt với tư duy mở, sáng tạo thì đây chính là cơ hội tháo gỡ những nút thắt để kinh tế - xã hội Việt Nam có thể tăng trưởng nhanh hơn, bền vững hơn. Nữ nhà báo Alexandra Garfinkle hỏi ChatGPT rằng nó có thay thế người làm báo không, nó đáp: 'Con người không có gì phải lo lắng'.",
      "chunk_text": "nhanh hơn, đặc biệt là cơ hội cho vùng sâu vùng xa, thu hẹp khoảng cách với các trung tâm lớn, để mỗi công dân Việt Nam trở thành một nhà sáng tạo. Chủ trương kinh tế số - xã hội số trong công cuộc chuyển đổi số của Việt Nam cần được tiếp tục nhanh hơn và thực chất hơn chứ không chỉ là những con số thành tích. Với sự vận dụng AI, kinh tế số - xã hội số nếu được triển khai triệt để, nhanh chóng và đặc biệt với tư duy mở, sáng tạo thì đây chính là cơ hội tháo gỡ những nút thắt để kinh tế - xã hội Việt Nam có thể tăng trưởng nhanh hơn, bền vững hơn. Nữ nhà báo Alexandra Garfinkle hỏi ChatGPT rằng nó có thay thế người làm báo không, nó đáp: 'Con người không có gì phải lo lắng'."
    },
    {
      "chunk_id": "184821_token_0000",
      "article_id": "184821",
      "score": 0.8709957003593445,
      "title": "Trí tuệ nhân tạo hỗ trợ kiến trúc sư vẽ nhà cho người Việt?",
      "category": "Khoa học công nghệ",
      "strategy": "token",
      "chunk_index": 0,
      "text": "Tiêu đề: Trí tuệ nhân tạo hỗ trợ kiến trúc sư vẽ nhà cho người Việt?\nMô tả: AI hỗ trợ kiến trúc sư - đây là xu hướng mới hình thành ở ngành kiến trúc Việt Nam, trong bối cảnh trí tuệ nhân tạo (AI) ngày càng được ứng dụng rộng khắp.\nChuyên mục: Khoa học công nghệ\nĐoạn nội dung:\nVài tháng trở lại đây, sự nổi lên củaChatGPTkhiến người dùng dành sự quan tâm chú ý nhiều hơn cho trí tuệ nhân tạo. Tuy vậy, các chương trình chatbot như ChatGPT chỉ là một phần nhỏ trong bức tranh toàn cảnh về lĩnh vực AI. Không chỉ có khả năng cho ra đời những đoạn văn bản dựa trên yêu cầu (text to text), AI giờ đây còn có thể tạo hình ảnh (text to image) hay ghi nhớ rồi bắt chước giọng nói để đọc đoạn văn bản (text to voice). Thực tế cho thấy, việc nghiên cứu ứng dụng khả năng của AI vào thực tế đang diễn ra ngày một nhanh hơn, đặc biệt là trong lĩnh vực kiến trúc. Midjourney (do David Holz phát triển), Dall-E (OpenAI) và Stable Diffusion (của nhóm CompVis, đại học Ludwig Maximilian Munich - Đức) là những chương trình AI được nhiều kiến trúc sư biết đến. Trong đó, Stable Diffusion hiện thu hút quan tâm hơn cả do được cung cấp miễn phí với nhiều khả năng tùy biến. Do còn quá mới, không phải ai cũng dễ tiếp cận và sử dụng thành thạo các công cụ AI nên ngày càng xuất hiện nhiều những hội nhóm về việc ứng dụng, đào tạo AI trên các trang mạng xã hội. Một vài người còn trực tiếp chia sẻ câu chuyện về việc ứng dụng AI vào trong công việc của mình. Chia sẻ vớiVietNamNet, KTS Lý Phương (Hà Nội) cho biết, khoảng 1 năm trở lại đây, cô đã thử mày mò nhằm nghiên cứu, ứng dụng một số công cụ AI vào công việc. Trong đó, Midjourney được nữ KTS này sử dụng nhằm lên ý tưởng, còn ChatGPT đóng vai trò trợ lý ảo hỗ trợ việc tra cứu. Sau một thời gian sử dụng, KTS Lý Phương cho rằng, ChatGPT đóng vai trò hỗ trợ khá đắc lực. “Khi cần tìm hiểu về hệ thống máy nước nóng để lắp đặt cho công trình, tôi có thể hỏi ChatGPT. Công cụ này sẽ tổng hợp thông tin về các hệ thống máy nước nóng khác nhau, ưu và nhược điểm cũng như giá cả của từng công nghệ. Nếu tự tổng hợp, tôi có thể mất vài tiếng, trong khi chỉ vài phút ChatGPT đã cho ra câu trả lời”, cô nói. Với Midjourney, nữ",
      "chunk_text": "Vài tháng trở lại đây, sự nổi lên củaChatGPTkhiến người dùng dành sự quan tâm chú ý nhiều hơn cho trí tuệ nhân tạo. Tuy vậy, các chương trình chatbot như ChatGPT chỉ là một phần nhỏ trong bức tranh toàn cảnh về lĩnh vực AI. Không chỉ có khả năng cho ra đời những đoạn văn bản dựa trên yêu cầu (text to text), AI giờ đây còn có thể tạo hình ảnh (text to image) hay ghi nhớ rồi bắt chước giọng nói để đọc đoạn văn bản (text to voice). Thực tế cho thấy, việc nghiên cứu ứng dụng khả năng của AI vào thực tế đang diễn ra ngày một nhanh hơn, đặc biệt là trong lĩnh vực kiến trúc. Midjourney (do David Holz phát triển), Dall-E (OpenAI) và Stable Diffusion (của nhóm CompVis, đại học Ludwig Maximilian Munich - Đức) là những chương trình AI được nhiều kiến trúc sư biết đến. Trong đó, Stable Diffusion hiện thu hút quan tâm hơn cả do được cung cấp miễn phí với nhiều khả năng tùy biến. Do còn quá mới, không phải ai cũng dễ tiếp cận và sử dụng thành thạo các công cụ AI nên ngày càng xuất hiện nhiều những hội nhóm về việc ứng dụng, đào tạo AI trên các trang mạng xã hội. Một vài người còn trực tiếp chia sẻ câu chuyện về việc ứng dụng AI vào trong công việc của mình. Chia sẻ vớiVietNamNet, KTS Lý Phương (Hà Nội) cho biết, khoảng 1 năm trở lại đây, cô đã thử mày mò nhằm nghiên cứu, ứng dụng một số công cụ AI vào công việc. Trong đó, Midjourney được nữ KTS này sử dụng nhằm lên ý tưởng, còn ChatGPT đóng vai trò trợ lý ảo hỗ trợ việc tra cứu. Sau một thời gian sử dụng, KTS Lý Phương cho rằng, ChatGPT đóng vai trò hỗ trợ khá đắc lực. “Khi cần tìm hiểu về hệ thống máy nước nóng để lắp đặt cho công trình, tôi có thể hỏi ChatGPT. Công cụ này sẽ tổng hợp thông tin về các hệ thống máy nước nóng khác nhau, ưu và nhược điểm cũng như giá cả của từng công nghệ. Nếu tự tổng hợp, tôi có thể mất vài tiếng, trong khi chỉ vài phút ChatGPT đã cho ra câu trả lời”, cô nói. Với Midjourney, nữ"
    }
  ]
}

[exit=0] elapsed=21.05s

'\nLoading weights:   0%|          | 0/391 [00:00<?, ?it/s]\nLoading weights: 100%|██████████| 391/391 [00:00<00:00, 6106.77it/s]\n{\n  "query": "Tin tức về công nghệ AI tại Việt Nam",\n  "results": [\n    {\n      "chunk_id": "65416_token_0002",\n      "article_id": "65416",\n      "score": 0.8897868990898132,\n      "title": "AI Việt góp phần định hình bối cảnh trí tuệ nhân tạo Đông Nam Á",\n      "category": "Khoa học công nghệ",\n      "strategy": "token",\n      "chunk_index": 2,\n      "text": "Tiêu đề: AI Việt góp phần định hình bối cảnh trí tuệ nhân tạo Đông Nam Á\\nMô tả: Với rào cản kỹ thuật được hạ thấp, các startup trí tuệ nhân tạo ở Đông Nam Á, trong đó có công ty AI Việt Nam có thể tập trung vào thế mạnh của mình là giải quyết vấn đề kinh doanh thực tế .\\nChuyên mục: Khoa học công nghệ\\nĐoạn nội dung:\\ncác doanh nghiệp mạnh hơn đến từ Mỹ, Trung Quốc... chưa có được. AI Hay hiện được cung cấp thông qua website và ứng dụng cùng tên trên các kho phần mềm của hai nền tảng di động iOS lẫn Android. Xuất hiện lần đầu vào tháng 6.2024, chỉ sau một năm hoạt động, AI Hay hiện có hơn 10 triệu lượt tải ứng dụng, xử lý thành công hơn 100 triệu câu hỏi mỗi tháng, đồng thời nhận được đánh giá 4,8/5 điểm từ hơn 140.000 người dùng thực tế.",\n      "chunk_text": "các doanh nghiệp mạnh hơn đến từ Mỹ, Trung Quốc... chưa có được. AI Hay hiện được cung cấp thông qua website và ứng dụng cùng tên trên các kho phần mềm của hai nền tảng di động iOS lẫn Android. Xuất hiện lần đầu vào tháng 6.2024, chỉ sau một năm hoạt động, AI Hay hiện có hơn 10 triệu lượt tải ứng dụng, xử lý thành công hơn 100 triệu câu hỏi mỗi tháng, đồng thời nhận được đánh giá 4,8/5 điểm từ hơn 140.000 người dùng thực tế."\n    },\n    {\n      "chunk_id": "65416_token_0000",\n      "article_id": "65416",\n      "score": 0.8880772590637207,\n      "title": "AI Việt góp phần định hình bối cảnh trí tuệ nhân tạo Đông Nam Á",\n      "category": "Khoa học công nghệ",\n      "strategy": "token",\n      "chunk_index": 0,\n      "text": "Tiêu đề: AI Việt góp phần định hình bối cảnh trí tuệ nhân tạo Đông Nam Á\\nMô tả: Với rào cản kỹ thuật được hạ thấp, các startup trí tuệ nhân tạo ở Đông Nam Á, trong đó có công ty AI Việt Nam có thể tập trung vào thế mạnh của mình là giải quyết vấn đề kinh doanh thực tế .\\nChuyên mục: Khoa học công nghệ\\nĐoạn nội dung:\\nCác khoản đầu tư mạo hiểm (VC) toàn cầu tiếp tục xoay quanh trí tuệ nhân tạo, với 49% trong tổng số 205,6 tỉ USD huy động được trong nửa đầu năm 2025 chảy vào các công ty AI, theo dữ liệu của Crunchbase. Phần lớn (gần 90 tỉ USD) trong tổng số 100,8 tỉ USD dành cho trí tuệ nhân tạo được đổ vào các công ty Mỹ. Dù điều đó khiến Đông Nam Á có vẻ mờ nhạt trên bản đồ AI toàn cầu, một số công ty trong khu vực, trong đó có doanh nghiệp AI Việt Nam, vẫn huy động được các khoản vốn đáng kể. Việt Nam có số lượng startup AI nhiều đáng kể tại Đông Nam Á Ảnh chụp màn hình TechInAsia Một vài trong số các công ty này tập trung vào AI có khả năng tự hành (Agentic AI), phát triển các giải pháp cho phép AI tự động hoàn thành nhiệm vụ thay cho người dùng. Giữa \\"một rừng\\" tên tuổi chủ yếu đến từ Singapore và Indonesia, trong danh sách 50 startup sáng giá của TechAsia có 2 doanh nghiệp Việt làm AI, nhưng hướng đi khác nhau. Trong đó, AI Hay tập trung phát triển nền tảng cộng đồng nhằm thỏa mãn nhu cầu hỏi đáp, tìm kiếm thông tin của hàng triệu người Việt. Doanh nghiệp còn lại thì tập trung cho giải pháp giúp nông dân nuôi tôm. Tháng 7 vừa qua, AI Hay - nền tảng kết hợp trí tuệ nhân tạo tạo sinh với mạng xã hội do các kỹ sư Việt Nam phát triển đã công bố gọi vốn thành công vòng series A với số tiền 10 triệu USD, nâng tổng vốn huy động của đơn vị lên 18 triệu USD, tiến gần hơn đến mục tiêu mang đến công cụ AI thông minh, dễ tiếp cận và phục vụ cuộc sống hàng ngày của người Việt. Theo báo cáo thị trường AI tiêu dùng Việt Nam năm 2025 của Decision Lab, AI Hay đứng thứ 6 trong danh sách 10 công cụ trí tuệ nhân tạo được sử dụng nhiều nhất Việt Nam trong quý 2/2025. Báo cáo nhận định dù các sản phẩm quốc tế đang chiếm ưu thế và mạnh mẽ, nền tảng AI \\"nội địa\\" vẫn ghi được dấu ấn nhờ sự gần gũi và thấu hiểu người",\n      "chunk_text": "Các khoản đầu tư mạo hiểm (VC) toàn cầu tiếp tục xoay quanh trí tuệ nhân tạo, với 49% trong tổng số 205,6 tỉ USD huy động được trong nửa đầu năm 2025 chảy vào các công ty AI, theo dữ liệu của Crunchbase. Phần lớn (gần 90 tỉ USD) trong tổng số 100,8 tỉ USD dành cho trí tuệ nhân tạo được đổ vào các công ty Mỹ. Dù điều đó khiến Đông Nam Á có vẻ mờ nhạt trên bản đồ AI toàn cầu, một số công ty trong khu vực, trong đó có doanh nghiệp AI Việt Nam, vẫn huy động được các khoản vốn đáng kể. Việt Nam có số lượng startup AI nhiều đáng kể tại Đông Nam Á Ảnh chụp màn hình TechInAsia Một vài trong số các công ty này tập trung vào AI có khả năng tự hành (Agentic AI), phát triển các giải pháp cho phép AI tự động hoàn thành nhiệm vụ thay cho người dùng. Giữa \\"một rừng\\" tên tuổi chủ yếu đến từ Singapore và Indonesia, trong danh sách 50 startup sáng giá của TechAsia có 2 doanh nghiệp Việt làm AI, nhưng hướng đi khác nhau. Trong đó, AI Hay tập trung phát triển nền tảng cộng đồng nhằm thỏa mãn nhu cầu hỏi đáp, tìm kiếm thông tin của hàng triệu người Việt. Doanh nghiệp còn lại thì tập trung cho giải pháp giúp nông dân nuôi tôm. Tháng 7 vừa qua, AI Hay - nền tảng kết hợp trí tuệ nhân tạo tạo sinh với mạng xã hội do các kỹ sư Việt Nam phát triển đã công bố gọi vốn thành công vòng series A với số tiền 10 triệu USD, nâng tổng vốn huy động của đơn vị lên 18 triệu USD, tiến gần hơn đến mục tiêu mang đến công cụ AI thông minh, dễ tiếp cận và phục vụ cuộc sống hàng ngày của người Việt. Theo báo cáo thị trường AI tiêu dùng Việt Nam năm 2025 của Decision Lab, AI Hay đứng thứ 6 trong danh sách 10 công cụ trí tuệ nhân tạo được sử dụng nhiều nhất Việt Nam trong quý 2/2025. Báo cáo nhận định dù các sản phẩm quốc tế đang chiếm ưu thế và mạnh mẽ, nền tảng AI \\"nội địa\\" vẫn ghi được dấu ấn nhờ sự gần gũi và thấu hiểu người"\n    },\n    {\n      "chunk_id": "65416_token_0001",\n      "article_id": "65416",\n      "score": 0.8763104677200317,\n      "title": "AI Việt góp phần định hình bối cảnh trí tuệ nhân tạo Đông Nam Á",\n      "category": "Khoa học công nghệ",\n      "strategy": "token",\n      "chunk_index": 1,\n      "text": "Tiêu đề: AI Việt góp phần định hình bối cảnh trí tuệ nhân tạo Đông Nam Á\\nMô tả: Với rào cản kỹ thuật được hạ thấp, các startup trí tuệ nhân tạo ở Đông Nam Á, trong đó có công ty AI Việt Nam có thể tập trung vào thế mạnh của mình là giải quyết vấn đề kinh doanh thực tế .\\nChuyên mục: Khoa học công nghệ\\nĐoạn nội dung:\\nhàng ngày của người Việt. Theo báo cáo thị trường AI tiêu dùng Việt Nam năm 2025 của Decision Lab, AI Hay đứng thứ 6 trong danh sách 10 công cụ trí tuệ nhân tạo được sử dụng nhiều nhất Việt Nam trong quý 2/2025. Báo cáo nhận định dù các sản phẩm quốc tế đang chiếm ưu thế và mạnh mẽ, nền tảng AI \\"nội địa\\" vẫn ghi được dấu ấn nhờ sự gần gũi và thấu hiểu người Việt. Nhận định này cũng được thể hiện qua việc nền tảng của Việt Nam đứng thứ 2 danh sách về mức độ hài lòng của người dùng (47%), chỉ đứng sau ChatGTP của OpenAI (51%). Công ty AI Việt nhận được mức độ hài lòng cao thứ 2 ngay tại thị trường quê hương Ảnh chụp màn hình \\"Chúng tôi tin rằng AI không chỉ dành cho chuyên gia, mà phải trở thành công cụ phổ thông, đến được với từng người Việt, bắt đầu từ sinh viên - những người sẽ kiến tạo tương lai đất nước\\", anh Trần Quang Đức, CEO AI Hay từng chia sẻ sau khi gọi vốn thành công gần đây. Ưu điểm của nền tảng này là giúp người dùng đặt bất kỳ câu hỏi nào và nhận lại kết quả chính xác, tin cậy, có trích dẫn minh bạch, đặc biệt phù hợp với văn hóa, ngôn ngữ Việt Nam. Bên cạnh việc hỗ trợ tiếp cận tri thức, công cụ còn xây dựng cộng đồng tương tác, nơi người dùng chia sẻ kiến thức, cùng thảo luận và đóng góp ý kiến, tạo ra môi trường học hỏi văn minh. Hướng đi này cũng tương đồng với nhiều startup AI khác tại Đông Nam Á, nơi công ty khởi nghiệp nhìn thấy cơ hội phát triển nhờ khả năng am hiểu văn hóa bản địa cũng như khu vực, điều mà các doanh nghiệp mạnh hơn đến từ Mỹ, Trung Quốc... chưa có được. AI Hay hiện được cung cấp thông qua website và ứng dụng cùng tên trên các kho phần mềm của hai nền tảng di động iOS lẫn Android. Xuất hiện lần đầu vào tháng 6.2024, chỉ sau một năm hoạt động, AI Hay hiện có hơn 10 triệu lượt tải ứng dụng, xử lý thành công hơn 100 triệu câu hỏi mỗi tháng, đồng thời nhận được",\n      "chunk_text": "hàng ngày của người Việt. Theo báo cáo thị trường AI tiêu dùng Việt Nam năm 2025 của Decision Lab, AI Hay đứng thứ 6 trong danh sách 10 công cụ trí tuệ nhân tạo được sử dụng nhiều nhất Việt Nam trong quý 2/2025. Báo cáo nhận định dù các sản phẩm quốc tế đang chiếm ưu thế và mạnh mẽ, nền tảng AI \\"nội địa\\" vẫn ghi được dấu ấn nhờ sự gần gũi và thấu hiểu người Việt. Nhận định này cũng được thể hiện qua việc nền tảng của Việt Nam đứng thứ 2 danh sách về mức độ hài lòng của người dùng (47%), chỉ đứng sau ChatGTP của OpenAI (51%). Công ty AI Việt nhận được mức độ hài lòng cao thứ 2 ngay tại thị trường quê hương Ảnh chụp màn hình \\"Chúng tôi tin rằng AI không chỉ dành cho chuyên gia, mà phải trở thành công cụ phổ thông, đến được với từng người Việt, bắt đầu từ sinh viên - những người sẽ kiến tạo tương lai đất nước\\", anh Trần Quang Đức, CEO AI Hay từng chia sẻ sau khi gọi vốn thành công gần đây. Ưu điểm của nền tảng này là giúp người dùng đặt bất kỳ câu hỏi nào và nhận lại kết quả chính xác, tin cậy, có trích dẫn minh bạch, đặc biệt phù hợp với văn hóa, ngôn ngữ Việt Nam. Bên cạnh việc hỗ trợ tiếp cận tri thức, công cụ còn xây dựng cộng đồng tương tác, nơi người dùng chia sẻ kiến thức, cùng thảo luận và đóng góp ý kiến, tạo ra môi trường học hỏi văn minh. Hướng đi này cũng tương đồng với nhiều startup AI khác tại Đông Nam Á, nơi công ty khởi nghiệp nhìn thấy cơ hội phát triển nhờ khả năng am hiểu văn hóa bản địa cũng như khu vực, điều mà các doanh nghiệp mạnh hơn đến từ Mỹ, Trung Quốc... chưa có được. AI Hay hiện được cung cấp thông qua website và ứng dụng cùng tên trên các kho phần mềm của hai nền tảng di động iOS lẫn Android. Xuất hiện lần đầu vào tháng 6.2024, chỉ sau một năm hoạt động, AI Hay hiện có hơn 10 triệu lượt tải ứng dụng, xử lý thành công hơn 100 triệu câu hỏi mỗi tháng, đồng thời nhận được"\n    },\n    {\n      "chunk_id": "44869_token_0002",\n      "article_id": "44869",\n      "score": 0.8724695444107056,\n      "title": "ChatGPT ra đời, vận hội cho Việt Nam từ AI",\n      "category": "Thời sự",\n      "strategy": "token",\n      "chunk_index": 2,\n      "text": "Tiêu đề: ChatGPT ra đời, vận hội cho Việt Nam từ AI\\nMô tả: ChatGPT ra đời đã hiện thực hóa khái niệm trợ lý trí tuệ nhân tạo (trợ lý AI).\\nChuyên mục: Thời sự\\nĐoạn nội dung:\\nnhanh hơn, đặc biệt là cơ hội cho vùng sâu vùng xa, thu hẹp khoảng cách với các trung tâm lớn, để mỗi công dân Việt Nam trở thành một nhà sáng tạo. Chủ trương kinh tế số - xã hội số trong công cuộc chuyển đổi số của Việt Nam cần được tiếp tục nhanh hơn và thực chất hơn chứ không chỉ là những con số thành tích. Với sự vận dụng AI, kinh tế số - xã hội số nếu được triển khai triệt để, nhanh chóng và đặc biệt với tư duy mở, sáng tạo thì đây chính là cơ hội tháo gỡ những nút thắt để kinh tế - xã hội Việt Nam có thể tăng trưởng nhanh hơn, bền vững hơn. Nữ nhà báo Alexandra Garfinkle hỏi ChatGPT rằng nó có thay thế người làm báo không, nó đáp: \'Con người không có gì phải lo lắng\'.",\n      "chunk_text": "nhanh hơn, đặc biệt là cơ hội cho vùng sâu vùng xa, thu hẹp khoảng cách với các trung tâm lớn, để mỗi công dân Việt Nam trở thành một nhà sáng tạo. Chủ trương kinh tế số - xã hội số trong công cuộc chuyển đổi số của Việt Nam cần được tiếp tục nhanh hơn và thực chất hơn chứ không chỉ là những con số thành tích. Với sự vận dụng AI, kinh tế số - xã hội số nếu được triển khai triệt để, nhanh chóng và đặc biệt với tư duy mở, sáng tạo thì đây chính là cơ hội tháo gỡ những nút thắt để kinh tế - xã hội Việt Nam có thể tăng trưởng nhanh hơn, bền vững hơn. Nữ nhà báo Alexandra Garfinkle hỏi ChatGPT rằng nó có thay thế người làm báo không, nó đáp: \'Con người không có gì phải lo lắng\'."\n    },\n    {\n      "chunk_id": "184821_token_0000",\n      "article_id": "184821",\n      "score": 0.8709957003593445,\n      "title": "Trí tuệ nhân tạo hỗ trợ kiến trúc sư vẽ nhà cho người Việt?",\n      "category": "Khoa học công nghệ",\n      "strategy": "token",\n      "chunk_index": 0,\n      "text": "Tiêu đề: Trí tuệ nhân tạo hỗ trợ kiến trúc sư vẽ nhà cho người Việt?\\nMô tả: AI hỗ trợ kiến trúc sư - đây là xu hướng mới hình thành ở ngành kiến trúc Việt Nam, trong bối cảnh trí tuệ nhân tạo (AI) ngày càng được ứng dụng rộng khắp.\\nChuyên mục: Khoa học công nghệ\\nĐoạn nội dung:\\nVài tháng trở lại đây, sự nổi lên củaChatGPTkhiến người dùng dành sự quan tâm chú ý nhiều hơn cho trí tuệ nhân tạo. Tuy vậy, các chương trình chatbot như ChatGPT chỉ là một phần nhỏ trong bức tranh toàn cảnh về lĩnh vực AI. Không chỉ có khả năng cho ra đời những đoạn văn bản dựa trên yêu cầu (text to text), AI giờ đây còn có thể tạo hình ảnh (text to image) hay ghi nhớ rồi bắt chước giọng nói để đọc đoạn văn bản (text to voice). Thực tế cho thấy, việc nghiên cứu ứng dụng khả năng của AI vào thực tế đang diễn ra ngày một nhanh hơn, đặc biệt là trong lĩnh vực kiến trúc. Midjourney (do David Holz phát triển), Dall-E (OpenAI) và Stable Diffusion (của nhóm CompVis, đại học Ludwig Maximilian Munich - Đức) là những chương trình AI được nhiều kiến trúc sư biết đến. Trong đó, Stable Diffusion hiện thu hút quan tâm hơn cả do được cung cấp miễn phí với nhiều khả năng tùy biến. Do còn quá mới, không phải ai cũng dễ tiếp cận và sử dụng thành thạo các công cụ AI nên ngày càng xuất hiện nhiều những hội nhóm về việc ứng dụng, đào tạo AI trên các trang mạng xã hội. Một vài người còn trực tiếp chia sẻ câu chuyện về việc ứng dụng AI vào trong công việc của mình. Chia sẻ vớiVietNamNet, KTS Lý Phương (Hà Nội) cho biết, khoảng 1 năm trở lại đây, cô đã thử mày mò nhằm nghiên cứu, ứng dụng một số công cụ AI vào công việc. Trong đó, Midjourney được nữ KTS này sử dụng nhằm lên ý tưởng, còn ChatGPT đóng vai trò trợ lý ảo hỗ trợ việc tra cứu. Sau một thời gian sử dụng, KTS Lý Phương cho rằng, ChatGPT đóng vai trò hỗ trợ khá đắc lực. “Khi cần tìm hiểu về hệ thống máy nước nóng để lắp đặt cho công trình, tôi có thể hỏi ChatGPT. Công cụ này sẽ tổng hợp thông tin về các hệ thống máy nước nóng khác nhau, ưu và nhược điểm cũng như giá cả của từng công nghệ. Nếu tự tổng hợp, tôi có thể mất vài tiếng, trong khi chỉ vài phút ChatGPT đã cho ra câu trả lời”, cô nói. Với Midjourney, nữ",\n      "chunk_text": "Vài tháng trở lại đây, sự nổi lên củaChatGPTkhiến người dùng dành sự quan tâm chú ý nhiều hơn cho trí tuệ nhân tạo. Tuy vậy, các chương trình chatbot như ChatGPT chỉ là một phần nhỏ trong bức tranh toàn cảnh về lĩnh vực AI. Không chỉ có khả năng cho ra đời những đoạn văn bản dựa trên yêu cầu (text to text), AI giờ đây còn có thể tạo hình ảnh (text to image) hay ghi nhớ rồi bắt chước giọng nói để đọc đoạn văn bản (text to voice). Thực tế cho thấy, việc nghiên cứu ứng dụng khả năng của AI vào thực tế đang diễn ra ngày một nhanh hơn, đặc biệt là trong lĩnh vực kiến trúc. Midjourney (do David Holz phát triển), Dall-E (OpenAI) và Stable Diffusion (của nhóm CompVis, đại học Ludwig Maximilian Munich - Đức) là những chương trình AI được nhiều kiến trúc sư biết đến. Trong đó, Stable Diffusion hiện thu hút quan tâm hơn cả do được cung cấp miễn phí với nhiều khả năng tùy biến. Do còn quá mới, không phải ai cũng dễ tiếp cận và sử dụng thành thạo các công cụ AI nên ngày càng xuất hiện nhiều những hội nhóm về việc ứng dụng, đào tạo AI trên các trang mạng xã hội. Một vài người còn trực tiếp chia sẻ câu chuyện về việc ứng dụng AI vào trong công việc của mình. Chia sẻ vớiVietNamNet, KTS Lý Phương (Hà Nội) cho biết, khoảng 1 năm trở lại đây, cô đã thử mày mò nhằm nghiên cứu, ứng dụng một số công cụ AI vào công việc. Trong đó, Midjourney được nữ KTS này sử dụng nhằm lên ý tưởng, còn ChatGPT đóng vai trò trợ lý ảo hỗ trợ việc tra cứu. Sau một thời gian sử dụng, KTS Lý Phương cho rằng, ChatGPT đóng vai trò hỗ trợ khá đắc lực. “Khi cần tìm hiểu về hệ thống máy nước nóng để lắp đặt cho công trình, tôi có thể hỏi ChatGPT. Công cụ này sẽ tổng hợp thông tin về các hệ thống máy nước nóng khác nhau, ưu và nhược điểm cũng như giá cả của từng công nghệ. Nếu tự tổng hợp, tôi có thể mất vài tiếng, trong khi chỉ vài phút ChatGPT đã cho ra câu trả lời”, cô nói. Với Midjourney, nữ"\n    }\n  ]\n}\n'

## 10. Eval retrieval trên 50 QA mẫu

Cell này đánh giá các dense index đã embed bằng qrels ở mức `article_id`. Mỗi retrieved chunk được xem là đúng nếu `article_id` của chunk nằm trong `source_article_ids` hoặc `article_id` của QA.

Metric chính để xếp hạng là `nDCG@10`. Các metric khác dùng để giải thích trade-off chất lượng/chi phí.

In [19]:
QA_PATH = "Dataset/QA_Claude/QA_output.csv"
QA_SAMPLE_SIZE = 153
EVAL_TOP_K = 10

qa_df = pd.read_csv(QA_PATH)
# if "is_possible" in qa_df.columns:
#     qa_df = qa_df[qa_df["is_possible"].astype(str).str.lower().isin(["true", "1", "yes"])]
# qa_df = qa_df.dropna(subset=["question"]).head(QA_SAMPLE_SIZE).copy()

print("QA samples:", len(qa_df))
display(qa_df[[col for col in ["id", "article_id", "question", "source_article_ids", "qa_type"] if col in qa_df.columns]].head())

QA samples: 152

,id,article_id,question,source_article_ids,qa_type
0,211640_1,211640,Những loại nội tạng động vật nào được khuyến c...,NaN,factoid
1,211640_2,211640,Quan niệm cho rằng thịt dê là thủ phạm duy nhấ...,NaN,event_summary
2,211640_3,211640,Tại sao nước dùng hầm xương hoặc nước lẩu lại ...,NaN,cause_effect
3,211640_4,211640,Hàm lượng purin trong cá nhỏ và nội tạng động ...,NaN,comparison
4,211640_5,211640,Đúng hay sai: 'Chỉ cần bỏ thịt dê và chuyển sa...,NaN,claim_verification

In [20]:
import math
import statistics
import numpy as np
from sentence_transformers import SentenceTransformer

from src.embed.embed_chunks import prepare_query_text
from src.embed.dense_search import load_index


def parse_qrels(row):
    values = set()
    for col in ["source_article_ids", "article_id"]:
        if col not in row or pd.isna(row[col]):
            continue
        raw = row[col]
        if isinstance(raw, (list, tuple, set)):
            parts = raw
        else:
            text = str(raw).strip()
            try:
                parsed = json.loads(text)
                parts = parsed if isinstance(parsed, list) else [parsed]
            except Exception:
                parts = text.replace(";", ",").replace("|", ",").split(",")
        for part in parts:
            value = str(part).strip().strip("[]'\"")
            if value and value.lower() not in {"nan", "none", ""}:
                values.add(value)
    return values


def dcg_at_k(relevances, k):
    return sum(rel / math.log2(idx + 2) for idx, rel in enumerate(relevances[:k]))


def metrics_for_results(results, relevant_article_ids, k=10):
    retrieved_article_ids = []
    seen_article_ids = set()
    for item in results:
        article_id = str(item.get("article_id"))
        if article_id in seen_article_ids:
            continue
        seen_article_ids.add(article_id)
        retrieved_article_ids.append(article_id)
        if len(retrieved_article_ids) >= k:
            break

    relevances = [1 if article_id in relevant_article_ids else 0 for article_id in retrieved_article_ids]
    ideal_relevances = [1] * min(len(relevant_article_ids), k)
    ideal_dcg = dcg_at_k(ideal_relevances, k)
    ndcg = dcg_at_k(relevances, k) / ideal_dcg if ideal_dcg else 0.0

    def recall_at(cutoff):
        found = set(retrieved_article_ids[:cutoff]) & relevant_article_ids
        return len(found) / len(relevant_article_ids) if relevant_article_ids else 0.0

    def hit_at(cutoff):
        return 1.0 if set(retrieved_article_ids[:cutoff]) & relevant_article_ids else 0.0

    mrr = 0.0
    for idx, article_id in enumerate(retrieved_article_ids[:k], start=1):
        if article_id in relevant_article_ids:
            mrr = 1.0 / idx
            break

    return {
        "nDCG@10": ndcg,
        "Recall@5": recall_at(5),
        "Recall@10": recall_at(10),
        "MRR@10": mrr,
        "Hit@1": hit_at(1),
        "Hit@5": hit_at(5),
    }


def percentile(values, pct):
    if not values:
        return 0.0
    values = sorted(values)
    index = min(len(values) - 1, math.ceil((pct / 100) * len(values)) - 1)
    return values[index]


def directory_size_mb(path):
    path = Path(path)
    return sum(file.stat().st_size for file in path.rglob("*") if file.is_file()) / (1024 * 1024)


def search_arrays(query, embeddings, metadata, model, top_k):
    query_vector = model.encode([prepare_query_text(query)], normalize_embeddings=True, show_progress_bar=False)
    query_array = np.asarray(query_vector, dtype=np.float32)[0]
    scores = embeddings @ query_array
    top_indices = np.argsort(scores)[::-1][:top_k]
    return [metadata[int(index)] | {"score": float(scores[int(index)])} for index in top_indices]

In [21]:
# Load model một lần để query evaluation không tải lại model theo từng query.
query_model = SentenceTransformer(MODEL_NAME)

eval_rows = []
per_query_rows = []

for strategy in STRATEGIES:
    index_dir = DENSE_OUTPUT_ROOT / strategy
    stats_path = index_dir / "embedding_stats.json"
    manifest_path = index_dir / "manifest.json"
    if not (index_dir / "embeddings.npy").exists():
        print(f"Skip {strategy}: missing embeddings.npy")
        continue

    embeddings, metadata = load_index(index_dir)
    stats = load_json(stats_path)
    manifest = load_json(manifest_path)
    query_latencies_ms = []
    metric_rows = []

    for _, qa in qa_df.iterrows():
        relevant_article_ids = parse_qrels(qa)
        if not relevant_article_ids:
            continue
        started = time.perf_counter()
        results = search_arrays(str(qa["question"]), embeddings, metadata, query_model, EVAL_TOP_K)
        latency_ms = (time.perf_counter() - started) * 1000
        query_latencies_ms.append(latency_ms)

        metrics = metrics_for_results(results, relevant_article_ids, k=EVAL_TOP_K)
        metric_rows.append(metrics)
        per_query_rows.append({
            "strategy": strategy,
            "qa_id": qa.get("id"),
            "qa_type": qa.get("qa_type"),
            "question": qa.get("question"),
            "relevant_article_ids": sorted(relevant_article_ids),
            "top_article_ids": [item.get("article_id") for item in results[:EVAL_TOP_K]],
            "latency_ms": latency_ms,
            **metrics,
        })

    if not metric_rows:
        continue

    aggregate = {key: float(np.mean([row[key] for row in metric_rows])) for key in metric_rows[0]}
    eval_rows.append({
        "Model": MODEL_NAME,
        "Chunking": strategy,
        "nDCG@10": aggregate["nDCG@10"],
        "Recall@5": aggregate["Recall@5"],
        "Recall@10": aggregate["Recall@10"],
        "MRR@10": aggregate["MRR@10"],
        "Hit@1": aggregate["Hit@1"],
        "Hit@5": aggregate["Hit@5"],
        "embedding_time_seconds": stats["elapsed_seconds"],
        "chunks_per_second": stats["chunks_per_second"],
        "query_latency_ms_avg": statistics.mean(query_latencies_ms),
        "query_latency_ms_p95": percentile(query_latencies_ms, 95),
        "index_size_mb": directory_size_mb(index_dir),
        "embedding_dimension": manifest["embedding_dimension"],
        "num_chunks": stats["chunks_embedded"],
        "avg_chunk_tokens": stats["token_stats"]["avg"],
        "queries": len(metric_rows),
    })

eval_df = pd.DataFrame(eval_rows)
if not eval_df.empty:
    eval_df = eval_df.sort_values(
        ["nDCG@10", "Recall@10", "query_latency_ms_avg"],
        ascending=[False, False, True],
    ).reset_index(drop=True)
    eval_df.insert(0, "Rank", range(1, len(eval_df) + 1))

display(eval_df)

per_query_df = pd.DataFrame(per_query_rows)
eval_output_dir = PROJECT_ROOT / "src" / "embed" / "output" / "eval"
eval_output_dir.mkdir(parents=True, exist_ok=True)
eval_df.to_csv(eval_output_dir / "leaderboard_qa50.csv", index=False, encoding="utf-8-sig")
per_query_df.to_json(eval_output_dir / "per_query_results_qa50.jsonl", orient="records", lines=True, force_ascii=False)
print("Saved leaderboard:", eval_output_dir / "leaderboard_qa50.csv")
print("Saved per-query results:", eval_output_dir / "per_query_results_qa50.jsonl")

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

,Rank,Model,Chunking,nDCG@10,Recall@5,Recall@10,MRR@10,Hit@1,Hit@5,embedding_time_seconds,chunks_per_second,query_latency_ms_avg,query_latency_ms_p95,index_size_mb,embedding_dimension,num_chunks,avg_chunk_tokens,queries
0,1,intfloat/multilingual-e5-large,token,0.788094,0.817982,0.837719,0.836842,0.763158,0.934211,2429.915227,9.9176,33.543827,40.145281,212.347048,1024,24099,397.9590,152
1,2,intfloat/multilingual-e5-large,structured,0.778245,0.817982,0.835526,0.825987,0.736842,0.934211,2577.720623,9.8785,33.488932,40.626828,224.141803,1024,25464,396.7930,152
2,3,intfloat/multilingual-e5-large,llamaindex,0.755538,0.780702,0.789474,0.817928,0.736842,0.907895,2916.000963,16.7959,51.272990,83.414858,332.691929,1024,48977,219.1943,152
3,4,intfloat/multilingual-e5-large,langchain_recursive,0.702540,0.721491,0.721491,0.782018,0.710526,0.861842,4261.312797,23.0342,68.850295,100.475502,578.294096,1024,98156,139.0185,152

Saved leaderboard: /content/Text-Mining---RAG-on-News/src/embed/output/eval/leaderboard_qa50.csv
Saved per-query results: /content/Text-Mining---RAG-on-News/src/embed/output/eval/per_query_results_qa50.jsonl

## 11. Notes đánh giá

Quy tắc đọc bảng:

- Metric xếp hạng chính: `nDCG@10`.
- Nếu `nDCG@10` gần nhau, ưu tiên `Recall@10` cao hơn và `query_latency_ms_avg` thấp hơn.
- Không so sánh các dòng nếu dùng khác query set hoặc khác qrels.
- Với E5, notebook dùng prefix `query: ` cho câu hỏi và `passage: ` cho chunk trong bước embed.
- Kết quả này là eval nhanh trên khoảng 50 QA mẫu, chưa thay thế evaluation đầy đủ cho báo cáo cuối.

Các câu hỏi cần trả lời từ leaderboard:

1. Strategy chunking nào ổn định nhất?
2. Model/chunking nào đạt retrieval tốt nhất theo `nDCG@10`?
3. Cấu hình nào trade-off tốt giữa chất lượng, latency và index size?
4. Cấu hình nào nên dùng cho pipeline RAG cuối cùng?